/* generated by orto */
#include <stdlib.h>

typedef struct Option_int Option_int;

struct Ref_int_cell;

typedef struct { struct Ref_int_cell* ptr; int expected_gen; } Ref_int;

struct Option_int {
    int tag;
    union {
        struct { int f0; } Some;
    } as;
};

struct Ref_int_cell { int gen; int value; };

int main(void);

int main(void) {
    struct Ref_int_cell* _cell_1 = malloc(sizeof(struct Ref_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 10;
    Ref_int a_1 = ((Ref_int){ .ptr = _cell_1, .expected_gen = 1 });
    Ref_int b_2 = a_1;
    Ref_int _r_3 = b_2;
    int _v_4 = 99;
    Option_int _assign_2;
    if (_r_3.ptr->gen == _r_3.expected_gen) {
        _r_3.ptr->value = _v_4;
        _assign_2 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _v_4 } } };
    } else {
        _assign_2 = (Option_int){ .tag = 1 };
    }
    (void)(_assign_2);
    Ref_int _r_6 = a_1;
    Option_int _deref_5;
    if (_r_6.ptr->gen == _r_6.expected_gen) {
        _deref_5 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_6.ptr->value } } };
    } else {
        _deref_5 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_7 = _deref_5;
    int match_result_8;
    switch (scrut_7.tag) {
        case 0: { /* Some */
            int _qq_v_3 = scrut_7.as.Some.f0;
            match_result_8 = _qq_v_3;
            break;
        }
        case 1: { /* None */
            abort();
            int _panic_9 = (int){0};
            match_result_8 = _panic_9;
            break;
        }
        default: abort();
    }
    return match_result_8;
}