/* generated by orto */
#include <stdlib.h>
#include <stddef.h>

struct Region_header { int gen; char* buffer; size_t buffer_size; size_t used; };
typedef struct { struct Region_header* header; int expected_gen; } Region;

typedef struct { struct Region_header* region; int offset; int len; int expected_gen; } Array_int;

int main(void);

int main(void) {
    int _n_1 = 1024;
    if (_n_1 < 0) abort();
    struct Region_header* _h_2 = malloc(sizeof(struct Region_header));
    if (!_h_2) abort();
    _h_2->gen = 1;
    _h_2->buffer = malloc((size_t)_n_1);
    if (!_h_2->buffer) abort();
    _h_2->buffer_size = (size_t)_n_1;
    _h_2->used = 0;
    Region _reg_3 = ((Region){ .header = _h_2, .expected_gen = 1 });
    Region r_1 = _reg_3;
    Region _r_4 = r_1;
    if (_r_4.header->gen != _r_4.expected_gen) abort();
    int _n_5 = 4;
    if (_n_5 < 0) abort();
    if (_r_4.header->used + (size_t)_n_5 * sizeof(int) > _r_4.header->buffer_size) abort();
    int _off_6 = (int)_r_4.header->used;
    _r_4.header->used += (size_t)_n_5 * sizeof(int);
    int* _slots_7 = (int*)(_r_4.header->buffer + _off_6);
    for (int _i_8 = 0; _i_8 < _n_5; _i_8++) _slots_7[_i_8] = 0;
    Array_int _arr_9 = ((Array_int){ .region = _r_4.header, .offset = _off_6, .len = _n_5, .expected_gen = _r_4.expected_gen });
    Array_int a_2 = _arr_9;
    Array_int _a_10 = a_2;
    int _i_11 = 0;
    if (_a_10.region->gen != _a_10.expected_gen) abort();
    if (_i_11 < 0 || _i_11 >= _a_10.len) abort();
    ((int*)(_a_10.region->buffer + _a_10.offset))[_i_11] = 1;
    (void)(0);
    Array_int _a_12 = a_2;
    int _i_13 = 1;
    if (_a_12.region->gen != _a_12.expected_gen) abort();
    if (_i_13 < 0 || _i_13 >= _a_12.len) abort();
    ((int*)(_a_12.region->buffer + _a_12.offset))[_i_13] = 2;
    (void)(0);
    Array_int _a_14 = a_2;
    int _i_15 = 2;
    if (_a_14.region->gen != _a_14.expected_gen) abort();
    if (_i_15 < 0 || _i_15 >= _a_14.len) abort();
    ((int*)(_a_14.region->buffer + _a_14.offset))[_i_15] = 3;
    (void)(0);
    Array_int _a_16 = a_2;
    int _i_17 = 3;
    if (_a_16.region->gen != _a_16.expected_gen) abort();
    if (_i_17 < 0 || _i_17 >= _a_16.len) abort();
    ((int*)(_a_16.region->buffer + _a_16.offset))[_i_17] = 4;
    (void)(0);
    Array_int _a_18 = a_2;
    int _i_19 = 0;
    if (_a_18.region->gen != _a_18.expected_gen) abort();
    if (_i_19 < 0 || _i_19 >= _a_18.len) abort();
    int _idx_20 = ((int*)(_a_18.region->buffer + _a_18.offset))[_i_19];
    Array_int _a_21 = a_2;
    int _i_22 = 1;
    if (_a_21.region->gen != _a_21.expected_gen) abort();
    if (_i_22 < 0 || _i_22 >= _a_21.len) abort();
    int _idx_23 = ((int*)(_a_21.region->buffer + _a_21.offset))[_i_22];
    Array_int _a_24 = a_2;
    int _i_25 = 2;
    if (_a_24.region->gen != _a_24.expected_gen) abort();
    if (_i_25 < 0 || _i_25 >= _a_24.len) abort();
    int _idx_26 = ((int*)(_a_24.region->buffer + _a_24.offset))[_i_25];
    Array_int _a_27 = a_2;
    int _i_28 = 3;
    if (_a_27.region->gen != _a_27.expected_gen) abort();
    if (_i_28 < 0 || _i_28 >= _a_27.len) abort();
    int _idx_29 = ((int*)(_a_27.region->buffer + _a_27.offset))[_i_28];
    int _let_result_30 = ((((_idx_20 + _idx_23) + _idx_26) + _idx_29) + a_2.len);
    if (r_1.header->gen == r_1.expected_gen) { free(r_1.header->buffer); r_1.header->buffer = NULL; r_1.header->buffer_size = 0; r_1.header->used = 0; r_1.header->gen++; }
    return _let_result_30;
}