/* generated by orto */
#include <stdlib.h>
#include <stddef.h>

struct Region_header { int gen; char* buffer; size_t buffer_size; size_t used; };
typedef struct { struct Region_header* header; int expected_gen; } Region;

typedef struct { struct Region_header* region; int offset; int len; int expected_gen; } Array_int;

int main(void);

int main(void) {
    int _n_1 = 1024;
    if (_n_1 < 0) abort();
    struct Region_header* _h_2 = malloc(sizeof(struct Region_header));
    if (!_h_2) abort();
    _h_2->gen = 1;
    _h_2->buffer = malloc((size_t)_n_1);
    if (!_h_2->buffer) abort();
    _h_2->buffer_size = (size_t)_n_1;
    _h_2->used = 0;
    Region _reg_3 = ((Region){ .header = _h_2, .expected_gen = 1 });
    Region r_1 = _reg_3;
    Region _r_4 = r_1;
    if (_r_4.header->gen != _r_4.expected_gen) abort();
    if (_r_4.header->used + (size_t)4 * sizeof(int) > _r_4.header->buffer_size) abort();
    int _off_5 = (int)_r_4.header->used;
    _r_4.header->used += (size_t)4 * sizeof(int);
    int* _slots_6 = (int*)(_r_4.header->buffer + _off_5);
    _slots_6[0] = 1;
    _slots_6[1] = 2;
    _slots_6[2] = 3;
    _slots_6[3] = 4;
    Array_int _arr_7 = ((Array_int){ .region = _r_4.header, .offset = _off_5, .len = 4, .expected_gen = _r_4.expected_gen });
    Array_int a_2 = _arr_7;
    Array_int _a_8 = a_2;
    int _i_9 = 0;
    if (_a_8.region->gen != _a_8.expected_gen) abort();
    if (_i_9 < 0 || _i_9 >= _a_8.len) abort();
    int _idx_10 = ((int*)(_a_8.region->buffer + _a_8.offset))[_i_9];
    Array_int _a_11 = a_2;
    int _i_12 = 1;
    if (_a_11.region->gen != _a_11.expected_gen) abort();
    if (_i_12 < 0 || _i_12 >= _a_11.len) abort();
    int _idx_13 = ((int*)(_a_11.region->buffer + _a_11.offset))[_i_12];
    Array_int _a_14 = a_2;
    int _i_15 = 2;
    if (_a_14.region->gen != _a_14.expected_gen) abort();
    if (_i_15 < 0 || _i_15 >= _a_14.len) abort();
    int _idx_16 = ((int*)(_a_14.region->buffer + _a_14.offset))[_i_15];
    Array_int _a_17 = a_2;
    int _i_18 = 3;
    if (_a_17.region->gen != _a_17.expected_gen) abort();
    if (_i_18 < 0 || _i_18 >= _a_17.len) abort();
    int _idx_19 = ((int*)(_a_17.region->buffer + _a_17.offset))[_i_18];
    int _let_result_20 = ((((_idx_10 + _idx_13) + _idx_16) + _idx_19) + a_2.len);
    if (r_1.header->gen == r_1.expected_gen) { free(r_1.header->buffer); r_1.header->buffer = NULL; r_1.header->buffer_size = 0; r_1.header->used = 0; r_1.header->gen++; }
    return _let_result_20;
}