/* generated by orto */
#include <stdlib.h>

struct Array_int_cell;

typedef struct { struct Array_int_cell* ptr; int expected_gen; int len; } Array_int;

struct Array_int_cell { int gen; int buffer[]; };

int main(void);

int main(void) {
    int _n_1 = 4;
    struct Array_int_cell* _cell_2 = malloc(sizeof(struct Array_int_cell) + (size_t)_n_1 * sizeof(int));
    if (!_cell_2) abort();
    _cell_2->gen = 1;
    for (int _i_4 = 0; _i_4 < _n_1; _i_4++) _cell_2->buffer[_i_4] = 0;
    Array_int _arr_3 = ((Array_int){ .ptr = _cell_2, .expected_gen = 1, .len = _n_1 });
    Array_int a_1 = _arr_3;
    Array_int _a_5 = a_1;
    int _i_6 = 0;
    if (_a_5.ptr->gen != _a_5.expected_gen) abort();
    if (_i_6 < 0 || _i_6 >= _a_5.len) abort();
    _a_5.ptr->buffer[_i_6] = 1;
    (void)(0);
    Array_int _a_7 = a_1;
    int _i_8 = 1;
    if (_a_7.ptr->gen != _a_7.expected_gen) abort();
    if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
    _a_7.ptr->buffer[_i_8] = 2;
    (void)(0);
    Array_int _a_9 = a_1;
    int _i_10 = 2;
    if (_a_9.ptr->gen != _a_9.expected_gen) abort();
    if (_i_10 < 0 || _i_10 >= _a_9.len) abort();
    _a_9.ptr->buffer[_i_10] = 3;
    (void)(0);
    Array_int _a_11 = a_1;
    int _i_12 = 3;
    if (_a_11.ptr->gen != _a_11.expected_gen) abort();
    if (_i_12 < 0 || _i_12 >= _a_11.len) abort();
    _a_11.ptr->buffer[_i_12] = 4;
    (void)(0);
    Array_int _a_13 = a_1;
    int _i_14 = 0;
    if (_a_13.ptr->gen != _a_13.expected_gen) abort();
    if (_i_14 < 0 || _i_14 >= _a_13.len) abort();
    int _idx_15 = _a_13.ptr->buffer[_i_14];
    Array_int _a_16 = a_1;
    int _i_17 = 1;
    if (_a_16.ptr->gen != _a_16.expected_gen) abort();
    if (_i_17 < 0 || _i_17 >= _a_16.len) abort();
    int _idx_18 = _a_16.ptr->buffer[_i_17];
    Array_int _a_19 = a_1;
    int _i_20 = 2;
    if (_a_19.ptr->gen != _a_19.expected_gen) abort();
    if (_i_20 < 0 || _i_20 >= _a_19.len) abort();
    int _idx_21 = _a_19.ptr->buffer[_i_20];
    Array_int _a_22 = a_1;
    int _i_23 = 3;
    if (_a_22.ptr->gen != _a_22.expected_gen) abort();
    if (_i_23 < 0 || _i_23 >= _a_22.len) abort();
    int _idx_24 = _a_22.ptr->buffer[_i_23];
    int _let_result_25 = ((((_idx_15 + _idx_18) + _idx_21) + _idx_24) + a_1.len);
    free(a_1.ptr);
    return _let_result_25;
}