/* generated by orto */
#include <stdlib.h>
#include <stddef.h>

struct Region_header { int gen; char* buffer; size_t buffer_size; size_t used; };
typedef struct { struct Region_header* header; int expected_gen; } Region;

typedef struct { int* ptr; int len; } Buf_int;

int main(void);

int main(void) {
    int _stor_1[5] = { 10, 20, 30, 40, 50 };
    Buf_int _buf_2 = ((Buf_int){ .ptr = _stor_1, .len = 5 });
    Buf_int a_1 = _buf_2;
    int _stor_3[5];
    for (int _i_5 = 0; _i_5 < 5; _i_5++) _stor_3[_i_5] = 1;
    Buf_int _buf_4 = ((Buf_int){ .ptr = _stor_3, .len = 5 });
    Buf_int b_2 = _buf_4;
    Buf_int _a_6 = b_2;
    int _i_7 = 2;
    _a_6.ptr[_i_7] = 99;
    (void)(0);
    Buf_int _a_8 = a_1;
    int _i_9 = 0;
    int _idx_10 = _a_8.ptr[_i_9];
    Buf_int _a_11 = a_1;
    int _i_12 = 4;
    int _idx_13 = _a_11.ptr[_i_12];
    Buf_int _a_14 = b_2;
    int _i_15 = 0;
    int _idx_16 = _a_14.ptr[_i_15];
    Buf_int _a_17 = b_2;
    int _i_18 = 2;
    int _idx_19 = _a_17.ptr[_i_18];
    Buf_int _a_20 = b_2;
    int _i_21 = 4;
    int _idx_22 = _a_20.ptr[_i_21];
    return ((((((_idx_10 + _idx_13) + _idx_16) + _idx_19) + _idx_22) + a_1.len) + b_2.len);
}