/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef int (*fn_int_int_to_int)(int, int);

typedef int (*fn_fn_int_int_to_int_int_int_to_int)(fn_int_int_to_int, int, int);

typedef int (*fn_fn_int_int_to_int_int_int_int_to_int)(fn_int_int_to_int, int, int, int);

int times(int a, int b);

int apply2(fn_int_int_to_int f, int a, int b);

int plus(int a, int b);

int fold3(fn_int_int_to_int f, int x, int y, int z);

int main(void);

int times(int a, int b) {
    return (a * b);
}

int apply2(fn_int_int_to_int f, int a, int b) {
    return f(a, b);
}

int plus(int a, int b) {
    return (a + b);
}

int fold3(fn_int_int_to_int f, int x, int y, int z) {
    return f(f(x, y), z);
}

int main(void) {
    int a_1 = apply2(plus, 10, 32);
    int b_2 = apply2(times, 6, 7);
    int c_3 = fold3(plus, 1, 2, 3);
    int d_4 = (5 + 5);
    return (((a_1 + b_2) + c_3) + d_4);
}