/* generated by orto */
#include <stdlib.h>

typedef struct Option_int Option_int;

struct Ref_int_cell;

typedef struct { struct Ref_int_cell* ptr; int expected_gen; } Ref_int;

struct Option_int {
    int tag;
    union {
        struct { int f0; } Some;
    } as;
};

struct Ref_int_cell { int gen; int value; };

int main(void);

int main(void) {
    struct Ref_int_cell* _cell_1 = malloc(sizeof(struct Ref_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 0;
    Ref_int c_1 = ((Ref_int){ .ptr = _cell_1, .expected_gen = 1 });
    Ref_int _r_3 = c_1;
    Option_int _deref_2;
    if (_r_3.ptr->gen == _r_3.expected_gen) {
        _deref_2 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_3.ptr->value } } };
    } else {
        _deref_2 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_4 = _deref_2;
    int match_result_5;
    switch (scrut_4.tag) {
        case 0: { /* Some */
            int _qq_v_2 = scrut_4.as.Some.f0;
            match_result_5 = _qq_v_2;
            break;
        }
        case 1: { /* None */
            match_result_5 = 0;
            break;
        }
        default: abort();
    }
    Ref_int _r_7 = c_1;
    int _v_8 = (match_result_5 + 1);
    Option_int _assign_6;
    if (_r_7.ptr->gen == _r_7.expected_gen) {
        _r_7.ptr->value = _v_8;
        _assign_6 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _v_8 } } };
    } else {
        _assign_6 = (Option_int){ .tag = 1 };
    }
    (void)(_assign_6);
    Ref_int _r_10 = c_1;
    Option_int _deref_9;
    if (_r_10.ptr->gen == _r_10.expected_gen) {
        _deref_9 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_10.ptr->value } } };
    } else {
        _deref_9 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_11 = _deref_9;
    int match_result_12;
    switch (scrut_11.tag) {
        case 0: { /* Some */
            int _qq_v_3 = scrut_11.as.Some.f0;
            match_result_12 = _qq_v_3;
            break;
        }
        case 1: { /* None */
            match_result_12 = 0;
            break;
        }
        default: abort();
    }
    Ref_int _r_14 = c_1;
    int _v_15 = (match_result_12 + 1);
    Option_int _assign_13;
    if (_r_14.ptr->gen == _r_14.expected_gen) {
        _r_14.ptr->value = _v_15;
        _assign_13 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _v_15 } } };
    } else {
        _assign_13 = (Option_int){ .tag = 1 };
    }
    (void)(_assign_13);
    Ref_int _r_17 = c_1;
    Option_int _deref_16;
    if (_r_17.ptr->gen == _r_17.expected_gen) {
        _deref_16 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_17.ptr->value } } };
    } else {
        _deref_16 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_18 = _deref_16;
    int match_result_19;
    switch (scrut_18.tag) {
        case 0: { /* Some */
            int _qq_v_4 = scrut_18.as.Some.f0;
            match_result_19 = _qq_v_4;
            break;
        }
        case 1: { /* None */
            match_result_19 = 0;
            break;
        }
        default: abort();
    }
    Ref_int _r_21 = c_1;
    int _v_22 = (match_result_19 + 1);
    Option_int _assign_20;
    if (_r_21.ptr->gen == _r_21.expected_gen) {
        _r_21.ptr->value = _v_22;
        _assign_20 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _v_22 } } };
    } else {
        _assign_20 = (Option_int){ .tag = 1 };
    }
    (void)(_assign_20);
    Ref_int _r_24 = c_1;
    Option_int _deref_23;
    if (_r_24.ptr->gen == _r_24.expected_gen) {
        _deref_23 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_24.ptr->value } } };
    } else {
        _deref_23 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_25 = _deref_23;
    int match_result_26;
    switch (scrut_25.tag) {
        case 0: { /* Some */
            int _qq_v_5 = scrut_25.as.Some.f0;
            match_result_26 = _qq_v_5;
            break;
        }
        case 1: { /* None */
            abort();
            int _panic_27 = (int){0};
            match_result_26 = _panic_27;
            break;
        }
        default: abort();
    }
    return match_result_26;
}