/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[23] = { 0x66, 0x69, 0x72, 0x73, 0x74, 0x20, 0x6c, 0x69, 0x6e, 0x65, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x20, 0x6c, 0x69, 0x6e, 0x65, 0x0a };
#define ORTO_STATIC_BYTES_LEN 23

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct file_handle__File file_handle__File;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef int (*fn_int_ptr_byte_int_to_int)(int, uint8_t*, int);

typedef file_handle__File (*fn_to_file_handle__File)(void);

typedef int (*fn_file_handle__File_Array_byte_to_int)(file_handle__File, Array_byte);

typedef int (*fn_int_to_int)(int);

struct file_handle__File {
    int fd;
};

extern int close(int fd);

extern int write(int fd, uint8_t* buf, int n);

extern int putchar(int c);

file_handle__File file_handle__open_stdout(void);

int file_handle__write_str(file_handle__File f, Array_byte s);

int main(void);

int file_handle__drop_File(file_handle__File f);

file_handle__File file_handle__open_stdout(void) {
    return ((file_handle__File){ .fd = 1 });
}

int file_handle__write_str(file_handle__File f, Array_byte s) {
    Array_byte _a_1 = s;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    (void)(write(f.fd, _data_2, s.len));
    return 0;
}

int main(void) {
    file_handle__File f_1 = file_handle__open_stdout();
    (void)(file_handle__write_str(f_1, ((Array_byte){ .slot = 0, .offset = 0, .len = 11, .expected_gen = 1 })));
    (void)(file_handle__write_str(f_1, ((Array_byte){ .slot = 0, .offset = 11, .len = 12, .expected_gen = 1 })));
    (void)(putchar(65));
    (void)(putchar(10));
    int _let_result_1 = 0;
    file_handle__drop_File(f_1);
    return _let_result_1;
}

int file_handle__drop_File(file_handle__File f) {
    (void)(close(f.fd));
    return 0;
}