/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[45] = { 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x76, 0x69, 0x61, 0x20, 0x69, 0x6f, 0x5f, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x0a, 0x2f, 0x74, 0x6d, 0x70, 0x2f, 0x6f, 0x72, 0x74, 0x6f, 0x5f, 0x69, 0x6f, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x74, 0x78, 0x74 };
#define ORTO_STATIC_BYTES_LEN 45

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct iouring__Ring iouring__Ring;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef int (*fn_iouring__Ring_Array_byte_int_int_to_int)(iouring__Ring, Array_byte, int, int);

typedef int (*fn_to_int)(void);

typedef int (*fn_iouring__Ring_int_Array_byte_int_to_int)(iouring__Ring, int, Array_byte, int);

typedef int (*fn_iouring__Ring_int_to_int)(iouring__Ring, int);

typedef int (*fn_Array_byte_to_int)(Array_byte);

typedef int (*fn_ptr_byte_int_ptr_byte_int_int_to_int)(uint8_t*, int, uint8_t*, int, int);

typedef int (*fn_int_to_int)(int);

typedef int (*fn_Array_byte_int_to_int)(Array_byte, int);

typedef int (*fn_ptr_byte_int_to_int)(uint8_t*, int);

typedef int (*fn_Array_byte_Array_byte_int_to_int)(Array_byte, Array_byte, int);

typedef int (*fn_ptr_byte_ptr_byte_int_int_to_int)(uint8_t*, uint8_t*, int, int);

typedef int (*fn_ptr_byte_to_int)(uint8_t*);

typedef uint8_t* (*fn_int_to_ptr_byte)(int);

typedef iouring__Ring (*fn_int_to_iouring__Ring)(int);

typedef int (*fn_iouring__Ring_to_bool)(iouring__Ring);

typedef Array_byte (*fn_Region_Array_byte_to_Array_byte)(Region, Array_byte);

typedef int (*fn_Region_iouring__Ring_Array_byte_to_int)(Region, iouring__Ring, Array_byte);

struct iouring__Ring {
    uint8_t* handle;
};

extern uint8_t* orto_ring_create(int entries);

extern int orto_ring_exit(uint8_t* handle);

extern int orto_ring_read(uint8_t* handle, int fd, uint8_t* buf, int len_, int offset);

extern int orto_ring_write(uint8_t* handle, int fd, uint8_t* buf, int len_, int offset);

extern int orto_ring_openat(uint8_t* handle, uint8_t* path, int flags, int mode);

extern int orto_ring_close(uint8_t* handle, int fd);

extern int orto_ring_fsync(uint8_t* handle, int fd);

extern int orto_ring_socket(uint8_t* handle, int domain, int type_, int protocol);

extern int orto_ring_connect(uint8_t* handle, int fd, uint8_t* addr, int addrlen);

extern int orto_ring_accept(uint8_t* handle, int fd);

extern int orto_ring_send(uint8_t* handle, int fd, uint8_t* buf, int len_, int flags);

extern int orto_ring_recv(uint8_t* handle, int fd, uint8_t* buf, int len_, int flags);

extern int open(uint8_t* path, int flags, int mode);

extern int close(int fd);

extern int read(int fd, uint8_t* buf, int n);

extern int write(int fd, uint8_t* buf, int n);

extern int lseek(int fd, int offset, int whence);

extern int socket(int domain, int type_, int protocol);

extern int bind(int fd, uint8_t* addr, int addrlen);

extern int listen(int fd, int backlog);

extern int accept(int fd, uint8_t* addr, int* addrlen);

extern int connect(int fd, uint8_t* addr, int addrlen);

extern int sendto(int fd, uint8_t* buf, int n, int flags, uint8_t* addr, int addrlen);

extern int recvfrom(int fd, uint8_t* buf, int n, int flags, uint8_t* addr, int* addrlen);

extern int getpid(void);

extern int* __errno_location(void);

extern int putchar(int c);

int file_io_uring__do_read(Region r, iouring__Ring ring, Array_byte path);

int file_io_uring__do_write(Region r, iouring__Ring ring, Array_byte path);

int sys__o_trunc(void);

int iouring__uring_read(iouring__Ring r, int fd, Array_byte buf, int offset);

int io__print_loop(Array_byte s, int i);

int io__print(Array_byte s);

int iouring__uring_close(iouring__Ring r, int fd);

Array_byte str__c_str(Region r, Array_byte s);

int sys__o_rdonly(void);

int sys__o_creat(void);

int str__copy_into(Array_byte dst, Array_byte src, int at);

int iouring__uring_open(iouring__Ring r, Array_byte path, int flags, int mode);

int iouring__uring_write(iouring__Ring r, int fd, Array_byte buf, int offset);

int sys__o_wronly(void);

int iouring__drop_Ring(iouring__Ring r);

int iouring__ring_failed(iouring__Ring r);

iouring__Ring iouring__ring_new(int entries);

int main(void);

int file_io_uring__do_read(Region r, iouring__Ring ring, Array_byte path) {
    int fd_1 = iouring__uring_open(ring, path, sys__o_rdonly(), 0);
    int tmp_1;
    if ((fd_1 < 0)) {
        return 3;
        tmp_1 = 0;
    } else {
        tmp_1 = 0;
    }
    (void)(tmp_1);
    Region _r_2 = r;
    if (ORTO_REGIONS[_r_2.slot].gen != _r_2.expected_gen) abort();
    int _n_3 = 256;
    if (_n_3 < 0) abort();
    if (ORTO_REGIONS[_r_2.slot].used + (size_t)_n_3 * sizeof(uint8_t) > ORTO_REGIONS[_r_2.slot].buffer_size) abort();
    int _off_4 = (int)ORTO_REGIONS[_r_2.slot].used;
    ORTO_REGIONS[_r_2.slot].used += (size_t)_n_3 * sizeof(uint8_t);
    uint8_t* _slots_5 = (uint8_t*)(ORTO_REGIONS[_r_2.slot].buffer + _off_4);
    for (int _i_6 = 0; _i_6 < _n_3; _i_6++) _slots_5[_i_6] = ((uint8_t)(0));
    Array_byte _arr_7 = ((Array_byte){ .slot = _r_2.slot, .offset = _off_4, .len = _n_3, .expected_gen = _r_2.expected_gen });
    Array_byte buf_2 = _arr_7;
    int n_3 = iouring__uring_read(ring, fd_1, buf_2, 0);
    (void)(iouring__uring_close(ring, fd_1));
    int tmp_8;
    if ((n_3 <= 0)) {
        return 4;
        tmp_8 = 0;
    } else {
        tmp_8 = 0;
    }
    (void)(tmp_8);
    Array_byte _a_9 = buf_2;
    int _lo_10 = 0;
    int _hi_11 = n_3;
    if (ORTO_REGIONS[_a_9.slot].gen != _a_9.expected_gen) abort();
    if (_lo_10 < 0 || _hi_11 < _lo_10 || _hi_11 > _a_9.len) abort();
    Array_byte _sl_12 = ((Array_byte){ .slot = _a_9.slot, .offset = _a_9.offset + _lo_10 * (int)sizeof(uint8_t), .len = _hi_11 - _lo_10, .expected_gen = _a_9.expected_gen });
    (void)(io__print(_sl_12));
    return 0;
}

int file_io_uring__do_write(Region r, iouring__Ring ring, Array_byte path) {
    int flags_1 = ((sys__o_wronly() + sys__o_creat()) + sys__o_trunc());
    int fd_2 = iouring__uring_open(ring, path, flags_1, 420);
    int tmp_1;
    if ((fd_2 < 0)) {
        return 1;
        tmp_1 = 0;
    } else {
        tmp_1 = 0;
    }
    (void)(tmp_1);
    Array_byte msg_3 = ((Array_byte){ .slot = 0, .offset = 0, .len = 19, .expected_gen = 1 });
    int n_4 = iouring__uring_write(ring, fd_2, msg_3, 0);
    (void)(iouring__uring_close(ring, fd_2));
    int tmp_2;
    if ((n_4 < 0)) {
        return 2;
        tmp_2 = 0;
    } else {
        tmp_2 = 0;
    }
    (void)(tmp_2);
    return 0;
}

int sys__o_trunc(void) {
    return 512;
}

int iouring__uring_read(iouring__Ring r, int fd, Array_byte buf, int offset) {
    Array_byte _a_1 = buf;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    return orto_ring_read(r.handle, fd, _data_2, buf.len, offset);
}

int io__print_loop(Array_byte s, int i) {
    int tmp_4;
    if ((i >= s.len)) {
        tmp_4 = 0;
    } else {
        Array_byte _a_1 = s;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        (void)(putchar(((int)(_idx_3))));
        tmp_4 = io__print_loop(s, (i + 1));
    }
    return tmp_4;
}

int io__print(Array_byte s) {
    return io__print_loop(s, 0);
}

int iouring__uring_close(iouring__Ring r, int fd) {
    return orto_ring_close(r.handle, fd);
}

Array_byte str__c_str(Region r, Array_byte s) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = (s.len + 1);
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_1 = _arr_6;
    (void)(str__copy_into(dst_1, s, 0));
    Array_byte _a_7 = dst_1;
    int _lo_8 = 0;
    int _hi_9 = s.len;
    if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
    if (_lo_8 < 0 || _hi_9 < _lo_8 || _hi_9 > _a_7.len) abort();
    Array_byte _sl_10 = ((Array_byte){ .slot = _a_7.slot, .offset = _a_7.offset + _lo_8 * (int)sizeof(uint8_t), .len = _hi_9 - _lo_8, .expected_gen = _a_7.expected_gen });
    return _sl_10;
}

int sys__o_rdonly(void) {
    return 0;
}

int sys__o_creat(void) {
    return 64;
}

int str__copy_into(Array_byte dst, Array_byte src, int at) {
    int i_1 = 0;
    while ((i_1 < src.len)) {
        Array_byte _a_3 = src;
        int _i_4 = i_1;
        if (ORTO_REGIONS[_a_3.slot].gen != _a_3.expected_gen) abort();
        if (_i_4 < 0 || _i_4 >= _a_3.len) abort();
        uint8_t _idx_5 = ((uint8_t*)(ORTO_REGIONS[_a_3.slot].buffer + _a_3.offset))[_i_4];
        Array_byte _a_1 = dst;
        int _i_2 = (at + i_1);
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = _idx_5;
        (void)(0);
        i_1 = (i_1 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return 0;
}

int iouring__uring_open(iouring__Ring r, Array_byte path, int flags, int mode) {
    Array_byte _a_1 = path;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    return orto_ring_openat(r.handle, _data_2, flags, mode);
}

int iouring__uring_write(iouring__Ring r, int fd, Array_byte buf, int offset) {
    Array_byte _a_1 = buf;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    return orto_ring_write(r.handle, fd, _data_2, buf.len, offset);
}

int sys__o_wronly(void) {
    return 1;
}

int iouring__drop_Ring(iouring__Ring r) {
    (void)(orto_ring_exit(r.handle));
    return 0;
}

int iouring__ring_failed(iouring__Ring r) {
    return ((r.handle) == NULL);
}

iouring__Ring iouring__ring_new(int entries) {
    return ((iouring__Ring){ .handle = orto_ring_create(entries) });
}

int main(void) {
    int _n_1 = 4096;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_1 = _reg_3;
    iouring__Ring ring_2 = iouring__ring_new(8);
    int tmp_4;
    if (iouring__ring_failed(ring_2)) {
        return 10;
        tmp_4 = 0;
    } else {
        tmp_4 = 0;
    }
    (void)(tmp_4);
    Array_byte path_3 = str__c_str(r_1, ((Array_byte){ .slot = 0, .offset = 19, .len = 26, .expected_gen = 1 }));
    int w_4 = file_io_uring__do_write(r_1, ring_2, path_3);
    int tmp_5;
    if ((w_4 != 0)) {
        return w_4;
        tmp_5 = 0;
    } else {
        tmp_5 = 0;
    }
    (void)(tmp_5);
    int _let_result_6 = file_io_uring__do_read(r_1, ring_2, path_3);
    iouring__drop_Ring(ring_2);
    int _let_result_7 = _let_result_6;
    drop_Region(r_1);
    return _let_result_7;
}