/* generated by orto */
#include <stdlib.h>

typedef int (*fn_int_to_int)(int);

int square(int x);

int main(void);

int classify(int n);

int square(int x) {
    return (x * x);
}

int main(void) {
    int a_1 = square(5);
    int b_2 = square(square(2));
    int c_3 = classify(a_1);
    int d_4 = classify((-7));
    int total_5 = (((a_1 + b_2) + c_3) + d_4);
    return total_5;
}

int classify(int n) {
    int tmp_2;
    if ((n < 0)) {
        tmp_2 = (-1);
    } else {
        int tmp_1;
        if ((n == 0)) {
            tmp_1 = 0;
        } else {
            tmp_1 = 1;
        }
        tmp_2 = tmp_1;
    }
    return tmp_2;
}