/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct { int slot; int offset; int len; int expected_gen; } Array_int;

typedef int (*fn_int_to_int)(int);

typedef double (*fn_float_to_float)(double);

typedef double (*fn_Array_int_to_float)(Array_int);

typedef int (*fn_float_to_int)(double);

extern int putchar(int c);

double float_basic__area_of_circle(double r);

double float_basic__average(Array_int xs);

int float_basic__classify(double x);

int float_basic__print_int(int n);

int main(void);

double float_basic__area_of_circle(double r) {
    return ((3.1415926500000002 * r) * r);
}

double float_basic__average(Array_int xs) {
    int sum_1 = 0;
    int _for_hi_565953388_2 = xs.len;
    int i_3 = 0;
    while ((i_3 < _for_hi_565953388_2)) {
        Array_int _a_1 = xs;
        int _i_2 = i_3;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = ((int*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        sum_1 = (sum_1 + _idx_3);
        (void)(0);
        (void)(0);
        i_3 = (i_3 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return (((double)(sum_1)) / ((double)(xs.len)));
}

int float_basic__classify(double x) {
    int tmp_4;
    if ((x != x)) {
        tmp_4 = (0 - 1);
    } else {
        int tmp_3;
        if ((x < 0.0)) {
            tmp_3 = 0;
        } else {
            int tmp_2;
            if ((x == 0.0)) {
                tmp_2 = 1;
            } else {
                int tmp_1;
                if ((x < 1.0)) {
                    tmp_1 = 2;
                } else {
                    tmp_1 = 3;
                }
                tmp_2 = tmp_1;
            }
            tmp_3 = tmp_2;
        }
        tmp_4 = tmp_3;
    }
    return tmp_4;
}

int float_basic__print_int(int n) {
    int tmp_2;
    if ((n < 0)) {
        (void)(putchar(45));
        tmp_2 = float_basic__print_int((0 - n));
    } else {
        int tmp_1;
        if ((n < 10)) {
            tmp_1 = putchar((48 + n));
        } else {
            (void)(float_basic__print_int((n / 10)));
            tmp_1 = putchar((48 + (n % 10)));
        }
        tmp_2 = tmp_1;
    }
    return tmp_2;
}

int main(void) {
    int _n_1 = 1024;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_1 = _reg_3;
    double a_2 = float_basic__area_of_circle(2.0);
    (void)(float_basic__print_int(((int)(a_2))));
    (void)(putchar(10));
    Region _r_4 = r_1;
    if (ORTO_REGIONS[_r_4.slot].gen != _r_4.expected_gen) abort();
    if (ORTO_REGIONS[_r_4.slot].used + (size_t)5 * sizeof(int) > ORTO_REGIONS[_r_4.slot].buffer_size) abort();
    int _off_5 = (int)ORTO_REGIONS[_r_4.slot].used;
    ORTO_REGIONS[_r_4.slot].used += (size_t)5 * sizeof(int);
    int* _slots_6 = (int*)(ORTO_REGIONS[_r_4.slot].buffer + _off_5);
    _slots_6[0] = 1;
    _slots_6[1] = 2;
    _slots_6[2] = 3;
    _slots_6[3] = 4;
    _slots_6[4] = 5;
    Array_int _arr_7 = ((Array_int){ .slot = _r_4.slot, .offset = _off_5, .len = 5, .expected_gen = _r_4.expected_gen });
    Array_int xs_3 = _arr_7;
    double m_4 = float_basic__average(xs_3);
    (void)(float_basic__print_int(((int)(m_4))));
    (void)(putchar(10));
    double bad_5 = (0.0 / 0.0);
    (void)(float_basic__print_int(float_basic__classify(bad_5)));
    (void)(putchar(10));
    double inf_6 = (1.0 / 0.0);
    (void)(float_basic__print_int(float_basic__classify(inf_6)));
    (void)(putchar(10));
    int _let_result_8 = 0;
    drop_Region(r_1);
    return _let_result_8;
}