/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct handler__Handler_bool handler__Handler_bool;

typedef struct handler__Handler_int handler__Handler_int;

typedef int (*fn_int_to_bool)(int);

typedef int (*fn_int_to_int)(int);

typedef int (*fn_handler__Handler_int_int_to_int)(handler__Handler_int, int);

typedef int (*fn_handler__Handler_bool_int_to_bool)(handler__Handler_bool, int);

struct handler__Handler_bool {
    int tag;
    union {
        struct { int f0; } handler__Constant;
        struct { fn_int_to_bool f0; } handler__Compute;
    } as;
};

struct handler__Handler_int {
    int tag;
    union {
        struct { int f0; } handler__Constant;
        struct { fn_int_to_int f0; } handler__Compute;
    } as;
};

int handler__run_bool(handler__Handler_bool h, int input);

int handler__always_true(int x);

int handler__run_int(handler__Handler_int h, int input);

int handler__square(int x);

int main(void);

int handler__run_bool(handler__Handler_bool h, int input) {
    handler__Handler_bool scrut_1 = h;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* handler__Constant */
            int v_1 = scrut_1.as.handler__Constant.f0;
            match_result_2 = v_1;
            break;
        }
        case 1: { /* handler__Compute */
            fn_int_to_int f_2 = scrut_1.as.handler__Compute.f0;
            match_result_2 = f_2(input);
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int handler__always_true(int x) {
    return (x == x);
}

int handler__run_int(handler__Handler_int h, int input) {
    handler__Handler_int scrut_1 = h;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* handler__Constant */
            int v_1 = scrut_1.as.handler__Constant.f0;
            match_result_2 = v_1;
            break;
        }
        case 1: { /* handler__Compute */
            fn_int_to_int f_2 = scrut_1.as.handler__Compute.f0;
            match_result_2 = f_2(input);
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int handler__square(int x) {
    return (x * x);
}

int main(void) {
    handler__Handler_int h1_1 = ((handler__Handler_int){ .tag = 0, .as = { .handler__Constant = { .f0 = 42 } } });
    handler__Handler_int h2_2 = ((handler__Handler_int){ .tag = 1, .as = { .handler__Compute = { .f0 = handler__square } } });
    handler__Handler_bool h3_3 = ((handler__Handler_bool){ .tag = 1, .as = { .handler__Compute = { .f0 = handler__always_true } } });
    int a_4 = handler__run_int(h1_1, 0);
    int b_5 = handler__run_int(h2_2, 7);
    int tmp_1;
    if (handler__run_bool(h3_3, 99)) {
        tmp_1 = 10;
    } else {
        tmp_1 = 0;
    }
    int c_6 = tmp_1;
    return ((a_4 + b_5) + c_6);
}