/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef int (*fn_int_to_int)(int);

typedef int (*fn_to_int)(void);

extern int putchar(int c);

int hello_putchar__print_int(int n);

int hello_putchar__print_digit(int d);

int hello_putchar__fact(int n);

int main(void);

int hello_putchar__print_newline(void);

int hello_putchar__print_int(int n) {
    int tmp_1;
    if ((n < 10)) {
        tmp_1 = hello_putchar__print_digit(n);
    } else {
        (void)(hello_putchar__print_int((n / 10)));
        tmp_1 = hello_putchar__print_digit((n % 10));
    }
    return tmp_1;
}

int hello_putchar__print_digit(int d) {
    return putchar((d + 48));
}

int hello_putchar__fact(int n) {
    int tmp_1;
    if ((n <= 1)) {
        tmp_1 = 1;
    } else {
        tmp_1 = (n * hello_putchar__fact((n - 1)));
    }
    return tmp_1;
}

int main(void) {
    (void)(hello_putchar__print_int(hello_putchar__fact(7)));
    (void)(hello_putchar__print_newline());
    return 0;
}

int hello_putchar__print_newline(void) {
    return putchar(10);
}