/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef int (*fn_int_to_int)(int);

typedef int (*fn_int_to_bool)(int);

typedef int (*fn_fn_int_to_int_int_to_int)(fn_int_to_int, int);

typedef int (*fn_fn_int_to_bool_int_to_bool)(fn_int_to_bool, int);

int higher_order__is_even(int x);

int higher_order__inc(int x);

int higher_order__twice(fn_int_to_int f, int x);

int higher_order__apply_int_bool(fn_int_to_bool f, int x);

int higher_order__dbl(int x);

int higher_order__add5(int x);

int main(void);

int higher_order__apply_int_int(fn_int_to_int f, int x);

int higher_order__is_even(int x) {
    return ((x % 2) == 0);
}

int higher_order__inc(int x) {
    return (x + 1);
}

int higher_order__twice(fn_int_to_int f, int x) {
    return f(f(x));
}

int higher_order__apply_int_bool(fn_int_to_bool f, int x) {
    return f(x);
}

int higher_order__dbl(int x) {
    return (x * 2);
}

int higher_order__add5(int x) {
    return (x + 5);
}

int main(void) {
    int a_1 = higher_order__twice(higher_order__inc, 10);
    int b_2 = higher_order__twice(higher_order__dbl, 3);
    int c_3 = higher_order__apply_int_int(higher_order__add5, 20);
    int d_bool_4 = higher_order__apply_int_bool(higher_order__is_even, 6);
    int tmp_1;
    if (d_bool_4) {
        tmp_1 = 100;
    } else {
        tmp_1 = 0;
    }
    int d_5 = tmp_1;
    fn_int_to_int f_6 = higher_order__inc;
    int e_7 = f_6(f_6(f_6(5)));
    return ((((a_1 + b_2) + c_3) + d_5) + e_7);
}

int higher_order__apply_int_int(fn_int_to_int f, int x) {
    return f(x);
}