/* generated by orto */
#include <stdlib.h>
#include <stddef.h>

struct Region_header { int gen; char* buffer; size_t buffer_size; size_t used; };
typedef struct { struct Region_header* header; int expected_gen; } Region;

typedef struct { struct Region_header* region; int offset; int len; int expected_gen; } Array_int;

typedef int (*fn_Array_int_Array_int_int_to_int)(Array_int, Array_int, int);

typedef int (*fn_Array_int_int_int_to_int)(Array_int, int, int);

int build_histogram(Array_int values, Array_int counters, int i);

int find_max(Array_int counters, int i, int best);

int main(void);

int build_histogram(Array_int values, Array_int counters, int i) {
    int tmp_9;
    if ((i < values.len)) {
        Array_int _a_1 = values;
        int _i_2 = i;
        if (_a_1.region->gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = ((int*)(_a_1.region->buffer + _a_1.offset))[_i_2];
        int v_1 = _idx_3;
        Array_int _a_4 = counters;
        int _i_5 = v_1;
        if (_a_4.region->gen != _a_4.expected_gen) abort();
        if (_i_5 < 0 || _i_5 >= _a_4.len) abort();
        int _idx_6 = ((int*)(_a_4.region->buffer + _a_4.offset))[_i_5];
        Array_int _a_7 = counters;
        int _i_8 = v_1;
        if (_a_7.region->gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        ((int*)(_a_7.region->buffer + _a_7.offset))[_i_8] = (_idx_6 + 1);
        (void)(0);
        tmp_9 = build_histogram(values, counters, (i + 1));
    } else {
        tmp_9 = 0;
    }
    return tmp_9;
}

int find_max(Array_int counters, int i, int best) {
    int tmp_5;
    if ((i < counters.len)) {
        Array_int _a_1 = counters;
        int _i_2 = i;
        if (_a_1.region->gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = ((int*)(_a_1.region->buffer + _a_1.offset))[_i_2];
        int v_1 = _idx_3;
        int tmp_4;
        if ((v_1 > best)) {
            tmp_4 = v_1;
        } else {
            tmp_4 = best;
        }
        int new_best_2 = tmp_4;
        tmp_5 = find_max(counters, (i + 1), new_best_2);
    } else {
        tmp_5 = best;
    }
    return tmp_5;
}

int main(void) {
    int _n_1 = 4096;
    if (_n_1 < 0) abort();
    struct Region_header* _h_2 = malloc(sizeof(struct Region_header));
    if (!_h_2) abort();
    _h_2->gen = 1;
    _h_2->buffer = malloc((size_t)_n_1);
    if (!_h_2->buffer) abort();
    _h_2->buffer_size = (size_t)_n_1;
    _h_2->used = 0;
    Region _reg_3 = ((Region){ .header = _h_2, .expected_gen = 1 });
    Region r_1 = _reg_3;
    Region _r_4 = r_1;
    if (_r_4.header->gen != _r_4.expected_gen) abort();
    int _n_5 = 8;
    if (_n_5 < 0) abort();
    if (_r_4.header->used + (size_t)_n_5 * sizeof(int) > _r_4.header->buffer_size) abort();
    int _off_6 = (int)_r_4.header->used;
    _r_4.header->used += (size_t)_n_5 * sizeof(int);
    int* _slots_7 = (int*)(_r_4.header->buffer + _off_6);
    for (int _i_8 = 0; _i_8 < _n_5; _i_8++) _slots_7[_i_8] = 0;
    Array_int _arr_9 = ((Array_int){ .region = _r_4.header, .offset = _off_6, .len = _n_5, .expected_gen = _r_4.expected_gen });
    Array_int values_2 = _arr_9;
    Array_int _a_10 = values_2;
    int _i_11 = 0;
    if (_a_10.region->gen != _a_10.expected_gen) abort();
    if (_i_11 < 0 || _i_11 >= _a_10.len) abort();
    ((int*)(_a_10.region->buffer + _a_10.offset))[_i_11] = 4;
    (void)(0);
    Array_int _a_12 = values_2;
    int _i_13 = 1;
    if (_a_12.region->gen != _a_12.expected_gen) abort();
    if (_i_13 < 0 || _i_13 >= _a_12.len) abort();
    ((int*)(_a_12.region->buffer + _a_12.offset))[_i_13] = 1;
    (void)(0);
    Array_int _a_14 = values_2;
    int _i_15 = 2;
    if (_a_14.region->gen != _a_14.expected_gen) abort();
    if (_i_15 < 0 || _i_15 >= _a_14.len) abort();
    ((int*)(_a_14.region->buffer + _a_14.offset))[_i_15] = 4;
    (void)(0);
    Array_int _a_16 = values_2;
    int _i_17 = 3;
    if (_a_16.region->gen != _a_16.expected_gen) abort();
    if (_i_17 < 0 || _i_17 >= _a_16.len) abort();
    ((int*)(_a_16.region->buffer + _a_16.offset))[_i_17] = 2;
    (void)(0);
    Array_int _a_18 = values_2;
    int _i_19 = 4;
    if (_a_18.region->gen != _a_18.expected_gen) abort();
    if (_i_19 < 0 || _i_19 >= _a_18.len) abort();
    ((int*)(_a_18.region->buffer + _a_18.offset))[_i_19] = 4;
    (void)(0);
    Array_int _a_20 = values_2;
    int _i_21 = 5;
    if (_a_20.region->gen != _a_20.expected_gen) abort();
    if (_i_21 < 0 || _i_21 >= _a_20.len) abort();
    ((int*)(_a_20.region->buffer + _a_20.offset))[_i_21] = 1;
    (void)(0);
    Array_int _a_22 = values_2;
    int _i_23 = 6;
    if (_a_22.region->gen != _a_22.expected_gen) abort();
    if (_i_23 < 0 || _i_23 >= _a_22.len) abort();
    ((int*)(_a_22.region->buffer + _a_22.offset))[_i_23] = 3;
    (void)(0);
    Array_int _a_24 = values_2;
    int _i_25 = 7;
    if (_a_24.region->gen != _a_24.expected_gen) abort();
    if (_i_25 < 0 || _i_25 >= _a_24.len) abort();
    ((int*)(_a_24.region->buffer + _a_24.offset))[_i_25] = 2;
    (void)(0);
    Region _r_26 = r_1;
    if (_r_26.header->gen != _r_26.expected_gen) abort();
    int _n_27 = 5;
    if (_n_27 < 0) abort();
    if (_r_26.header->used + (size_t)_n_27 * sizeof(int) > _r_26.header->buffer_size) abort();
    int _off_28 = (int)_r_26.header->used;
    _r_26.header->used += (size_t)_n_27 * sizeof(int);
    int* _slots_29 = (int*)(_r_26.header->buffer + _off_28);
    for (int _i_30 = 0; _i_30 < _n_27; _i_30++) _slots_29[_i_30] = 0;
    Array_int _arr_31 = ((Array_int){ .region = _r_26.header, .offset = _off_28, .len = _n_27, .expected_gen = _r_26.expected_gen });
    Array_int counters_3 = _arr_31;
    (void)(build_histogram(values_2, counters_3, 0));
    int _let_result_32 = find_max(counters_3, 0, 0);
    if (r_1.header->gen == r_1.expected_gen) { free(r_1.header->buffer); r_1.header->buffer = NULL; r_1.header->buffer_size = 0; r_1.header->used = 0; r_1.header->gen++; }
    return _let_result_32;
}