/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_int;

typedef int (*fn_Array_int_int_int_to_int)(Array_int, int, int);

typedef int (*fn_Array_int_Array_int_int_to_int)(Array_int, Array_int, int);

int histogram__find_max(Array_int counters, int i, int best);

int histogram__build_histogram(Array_int values, Array_int counters, int i);

int main(void);

int histogram__find_max(Array_int counters, int i, int best) {
    int tmp_5;
    if ((i < counters.len)) {
        Array_int _a_1 = counters;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = ((int*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        int v_1 = _idx_3;
        int tmp_4;
        if ((v_1 > best)) {
            tmp_4 = v_1;
        } else {
            tmp_4 = best;
        }
        int new_best_2 = tmp_4;
        tmp_5 = histogram__find_max(counters, (i + 1), new_best_2);
    } else {
        tmp_5 = best;
    }
    return tmp_5;
}

int histogram__build_histogram(Array_int values, Array_int counters, int i) {
    int tmp_9;
    if ((i < values.len)) {
        Array_int _a_1 = values;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = ((int*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        int v_1 = _idx_3;
        Array_int _a_6 = counters;
        int _i_7 = v_1;
        if (ORTO_REGIONS[_a_6.slot].gen != _a_6.expected_gen) abort();
        if (_i_7 < 0 || _i_7 >= _a_6.len) abort();
        int _idx_8 = ((int*)(ORTO_REGIONS[_a_6.slot].buffer + _a_6.offset))[_i_7];
        Array_int _a_4 = counters;
        int _i_5 = v_1;
        if (ORTO_REGIONS[_a_4.slot].gen != _a_4.expected_gen) abort();
        if (_i_5 < 0 || _i_5 >= _a_4.len) abort();
        ((int*)(ORTO_REGIONS[_a_4.slot].buffer + _a_4.offset))[_i_5] = (_idx_8 + 1);
        (void)(0);
        tmp_9 = histogram__build_histogram(values, counters, (i + 1));
    } else {
        tmp_9 = 0;
    }
    return tmp_9;
}

int main(void) {
    int _n_1 = 4096;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_1 = _reg_3;
    Region _r_4 = r_1;
    if (ORTO_REGIONS[_r_4.slot].gen != _r_4.expected_gen) abort();
    if (ORTO_REGIONS[_r_4.slot].used + (size_t)8 * sizeof(int) > ORTO_REGIONS[_r_4.slot].buffer_size) abort();
    int _off_5 = (int)ORTO_REGIONS[_r_4.slot].used;
    ORTO_REGIONS[_r_4.slot].used += (size_t)8 * sizeof(int);
    int* _slots_6 = (int*)(ORTO_REGIONS[_r_4.slot].buffer + _off_5);
    _slots_6[0] = 4;
    _slots_6[1] = 1;
    _slots_6[2] = 4;
    _slots_6[3] = 2;
    _slots_6[4] = 4;
    _slots_6[5] = 1;
    _slots_6[6] = 3;
    _slots_6[7] = 2;
    Array_int _arr_7 = ((Array_int){ .slot = _r_4.slot, .offset = _off_5, .len = 8, .expected_gen = _r_4.expected_gen });
    Array_int values_2 = _arr_7;
    Region _r_8 = r_1;
    if (ORTO_REGIONS[_r_8.slot].gen != _r_8.expected_gen) abort();
    int _n_9 = 5;
    if (_n_9 < 0) abort();
    if (ORTO_REGIONS[_r_8.slot].used + (size_t)_n_9 * sizeof(int) > ORTO_REGIONS[_r_8.slot].buffer_size) abort();
    int _off_10 = (int)ORTO_REGIONS[_r_8.slot].used;
    ORTO_REGIONS[_r_8.slot].used += (size_t)_n_9 * sizeof(int);
    int* _slots_11 = (int*)(ORTO_REGIONS[_r_8.slot].buffer + _off_10);
    for (int _i_12 = 0; _i_12 < _n_9; _i_12++) _slots_11[_i_12] = 0;
    Array_int _arr_13 = ((Array_int){ .slot = _r_8.slot, .offset = _off_10, .len = _n_9, .expected_gen = _r_8.expected_gen });
    Array_int counters_3 = _arr_13;
    (void)(histogram__build_histogram(values_2, counters_3, 0));
    int _let_result_14 = histogram__find_max(counters_3, 0, 0);
    if (ORTO_REGIONS[r_1.slot].gen == r_1.expected_gen) { if (!ORTO_REGIONS[r_1.slot].is_stack) free(ORTO_REGIONS[r_1.slot].buffer); ORTO_REGIONS[r_1.slot].buffer = NULL; ORTO_REGIONS[r_1.slot].buffer_size = 0; ORTO_REGIONS[r_1.slot].used = 0; ORTO_REGIONS[r_1.slot].gen++; ORTO_REGIONS[r_1.slot].next_free = ORTO_REGION_FREE_HEAD; ORTO_REGION_FREE_HEAD = r_1.slot; }
    return _let_result_14;
}