/* generated by orto */
#include <stdlib.h>

struct Array_int_cell;

typedef struct { struct Array_int_cell* ptr; int expected_gen; int len; } Array_int;

typedef Array_int (*fn_Array_int_Array_int_int_to_Array_int)(Array_int, Array_int, int);

typedef int (*fn_Array_int_int_int_to_int)(Array_int, int, int);

struct Array_int_cell { int gen; int buffer[]; };

Array_int build_histogram(Array_int values, Array_int counters, int i);

int find_max(Array_int counters, int i, int best);

int main(void);

Array_int build_histogram(Array_int values, Array_int counters, int i) {
    Array_int tmp_10;
    if ((i < values.len)) {
        Array_int _a_1 = values;
        int _i_2 = i;
        if (_a_1.ptr->gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = _a_1.ptr->buffer[_i_2];
        int v_2 = _idx_3;
        Array_int _a_4 = counters;
        int _i_5 = v_2;
        if (_a_4.ptr->gen != _a_4.expected_gen) abort();
        if (_i_5 < 0 || _i_5 >= _a_4.len) abort();
        int _idx_6 = _a_4.ptr->buffer[_i_5];
        Array_int _a_7 = counters;
        int _i_8 = v_2;
        if (_a_7.ptr->gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        _a_7.ptr->buffer[_i_8] = (_idx_6 + 1);
        (void)(0);
        tmp_10 = build_histogram(values, counters, (i + 1));
    } else {
        Array_int values_1 = values;
        Array_int _let_result_9 = counters;
        free(values_1.ptr);
        tmp_10 = _let_result_9;
    }
    return tmp_10;
}

int find_max(Array_int counters, int i, int best) {
    int tmp_6;
    if ((i < counters.len)) {
        Array_int _a_1 = counters;
        int _i_2 = i;
        if (_a_1.ptr->gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        int _idx_3 = _a_1.ptr->buffer[_i_2];
        int v_2 = _idx_3;
        int tmp_4;
        if ((v_2 > best)) {
            tmp_4 = v_2;
        } else {
            tmp_4 = best;
        }
        int new_best_3 = tmp_4;
        tmp_6 = find_max(counters, (i + 1), new_best_3);
    } else {
        Array_int counters_1 = counters;
        int _let_result_5 = best;
        free(counters_1.ptr);
        tmp_6 = _let_result_5;
    }
    return tmp_6;
}

int main(void) {
    int _n_1 = 8;
    struct Array_int_cell* _cell_2 = malloc(sizeof(struct Array_int_cell) + (size_t)_n_1 * sizeof(int));
    if (!_cell_2) abort();
    _cell_2->gen = 1;
    for (int _i_4 = 0; _i_4 < _n_1; _i_4++) _cell_2->buffer[_i_4] = 0;
    Array_int _arr_3 = ((Array_int){ .ptr = _cell_2, .expected_gen = 1, .len = _n_1 });
    Array_int values_1 = _arr_3;
    Array_int _a_5 = values_1;
    int _i_6 = 0;
    if (_a_5.ptr->gen != _a_5.expected_gen) abort();
    if (_i_6 < 0 || _i_6 >= _a_5.len) abort();
    _a_5.ptr->buffer[_i_6] = 4;
    (void)(0);
    Array_int _a_7 = values_1;
    int _i_8 = 1;
    if (_a_7.ptr->gen != _a_7.expected_gen) abort();
    if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
    _a_7.ptr->buffer[_i_8] = 1;
    (void)(0);
    Array_int _a_9 = values_1;
    int _i_10 = 2;
    if (_a_9.ptr->gen != _a_9.expected_gen) abort();
    if (_i_10 < 0 || _i_10 >= _a_9.len) abort();
    _a_9.ptr->buffer[_i_10] = 4;
    (void)(0);
    Array_int _a_11 = values_1;
    int _i_12 = 3;
    if (_a_11.ptr->gen != _a_11.expected_gen) abort();
    if (_i_12 < 0 || _i_12 >= _a_11.len) abort();
    _a_11.ptr->buffer[_i_12] = 2;
    (void)(0);
    Array_int _a_13 = values_1;
    int _i_14 = 4;
    if (_a_13.ptr->gen != _a_13.expected_gen) abort();
    if (_i_14 < 0 || _i_14 >= _a_13.len) abort();
    _a_13.ptr->buffer[_i_14] = 4;
    (void)(0);
    Array_int _a_15 = values_1;
    int _i_16 = 5;
    if (_a_15.ptr->gen != _a_15.expected_gen) abort();
    if (_i_16 < 0 || _i_16 >= _a_15.len) abort();
    _a_15.ptr->buffer[_i_16] = 1;
    (void)(0);
    Array_int _a_17 = values_1;
    int _i_18 = 6;
    if (_a_17.ptr->gen != _a_17.expected_gen) abort();
    if (_i_18 < 0 || _i_18 >= _a_17.len) abort();
    _a_17.ptr->buffer[_i_18] = 3;
    (void)(0);
    Array_int _a_19 = values_1;
    int _i_20 = 7;
    if (_a_19.ptr->gen != _a_19.expected_gen) abort();
    if (_i_20 < 0 || _i_20 >= _a_19.len) abort();
    _a_19.ptr->buffer[_i_20] = 2;
    (void)(0);
    int _n_21 = 5;
    struct Array_int_cell* _cell_22 = malloc(sizeof(struct Array_int_cell) + (size_t)_n_21 * sizeof(int));
    if (!_cell_22) abort();
    _cell_22->gen = 1;
    for (int _i_24 = 0; _i_24 < _n_21; _i_24++) _cell_22->buffer[_i_24] = 0;
    Array_int _arr_23 = ((Array_int){ .ptr = _cell_22, .expected_gen = 1, .len = _n_21 });
    Array_int counters_2 = _arr_23;
    Array_int counters_3 = build_histogram(values_1, counters_2, 0);
    return find_max(counters_3, 0, 0);
}