/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[118] = { 0x2f, 0x74, 0x6d, 0x70, 0x2f, 0x6f, 0x72, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x31, 0x2e, 0x74, 0x78, 0x74, 0x2f, 0x74, 0x6d, 0x70, 0x2f, 0x6f, 0x72, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x32, 0x2e, 0x74, 0x78, 0x74, 0x2f, 0x74, 0x6d, 0x70, 0x2f, 0x6f, 0x72, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x33, 0x2e, 0x74, 0x78, 0x74, 0x41, 0x41, 0x41, 0x42, 0x42, 0x43, 0x43, 0x43, 0x43, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x20, 0x72, 0x65, 0x61, 0x64, 0x73, 0x3a, 0x20, 0x20, 0x6f, 0x70, 0x73, 0x2c, 0x20, 0x20, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2c, 0x20, 0x31, 0x20, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x20, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c };
#define ORTO_STATIC_BYTES_LEN 118

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct iouring__Completion iouring__Completion;

typedef struct iouring__Ring iouring__Ring;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_Array_byte;

typedef int (*fn_int_to_int)(int);

typedef int (*fn_Array_byte_int_to_int)(Array_byte, int);

typedef int (*fn_Array_Array_byte_to_int)(Array_Array_byte);

typedef int (*fn_Array_byte_Array_byte_int_to_int)(Array_byte, Array_byte, int);

typedef int (*fn_ptr_byte_int_to_int)(uint8_t*, int);

typedef int (*fn_ptr_byte_int_ptr_byte_int_int_int_to_int)(uint8_t*, int, uint8_t*, int, int, int);

typedef int (*fn_iouring__Ring_Array_byte_int_int_to_int)(iouring__Ring, Array_byte, int, int);

typedef int (*fn_to_int)(void);

typedef int (*fn_iouring__Ring_int_Array_byte_int_to_int)(iouring__Ring, int, Array_byte, int);

typedef int (*fn_iouring__Ring_int_to_int)(iouring__Ring, int);

typedef int (*fn_ptr_byte_ptr_byte_int_int_to_int)(uint8_t*, uint8_t*, int, int);

typedef int (*fn_ptr_byte_int_ptr_byte_int_int_to_int)(uint8_t*, int, uint8_t*, int, int);

typedef int (*fn_ptr_byte_to_int)(uint8_t*);

typedef int (*fn_ptr_byte_ptr_int_to_int)(uint8_t*, int*);

typedef uint8_t* (*fn_int_to_ptr_byte)(int);

typedef iouring__Ring (*fn_int_to_iouring__Ring)(int);

typedef int (*fn_iouring__Ring_to_bool)(iouring__Ring);

typedef Array_byte (*fn_Region_Array_byte_to_Array_byte)(Region, Array_byte);

typedef int (*fn_iouring__Ring_Array_byte_Array_byte_to_int)(iouring__Ring, Array_byte, Array_byte);

typedef int (*fn_iouring__Ring_int_Array_byte_int_int_to_int)(iouring__Ring, int, Array_byte, int, int);

typedef int (*fn_iouring__Ring_to_int)(iouring__Ring);

typedef iouring__Completion (*fn_iouring__Ring_to_iouring__Completion)(iouring__Ring);

typedef int (*fn_Array_byte_to_int)(Array_byte);

typedef Array_byte (*fn_Region_Array_Array_byte_to_Array_byte)(Region, Array_Array_byte);

typedef Array_byte (*fn_Region_int_to_Array_byte)(Region, int);

struct iouring__Completion {
    int id;
    int res;
};

struct iouring__Ring {
    uint8_t* handle;
};

extern uint8_t* orto_ring_create(int entries);

extern int orto_ring_exit(uint8_t* handle);

extern int orto_ring_read(uint8_t* handle, int fd, uint8_t* buf, int len_, int offset);

extern int orto_ring_write(uint8_t* handle, int fd, uint8_t* buf, int len_, int offset);

extern int orto_ring_openat(uint8_t* handle, uint8_t* path, int flags, int mode);

extern int orto_ring_close(uint8_t* handle, int fd);

extern int orto_ring_fsync(uint8_t* handle, int fd);

extern int orto_ring_socket(uint8_t* handle, int domain, int type_, int protocol);

extern int orto_ring_connect(uint8_t* handle, int fd, uint8_t* addr, int addrlen);

extern int orto_ring_accept(uint8_t* handle, int fd);

extern int orto_ring_send(uint8_t* handle, int fd, uint8_t* buf, int len_, int flags);

extern int orto_ring_recv(uint8_t* handle, int fd, uint8_t* buf, int len_, int flags);

extern int orto_ring_submit_read(uint8_t* handle, int fd, uint8_t* buf, int len_, int offset, int user_data);

extern int orto_ring_submit_write(uint8_t* handle, int fd, uint8_t* buf, int len_, int offset, int user_data);

extern int orto_ring_submit_send(uint8_t* handle, int fd, uint8_t* buf, int len_, int flags, int user_data);

extern int orto_ring_submit_recv(uint8_t* handle, int fd, uint8_t* buf, int len_, int flags, int user_data);

extern int orto_ring_flush(uint8_t* handle);

extern int orto_ring_wait_one(uint8_t* handle, int* out_id);

extern int orto_ring_peek_one(uint8_t* handle, int* out_id, int* out_res);

extern int open(uint8_t* path, int flags, int mode);

extern int close(int fd);

extern int read(int fd, uint8_t* buf, int n);

extern int write(int fd, uint8_t* buf, int n);

extern int lseek(int fd, int offset, int whence);

extern int socket(int domain, int type_, int protocol);

extern int bind(int fd, uint8_t* addr, int addrlen);

extern int listen(int fd, int backlog);

extern int accept(int fd, uint8_t* addr, int* addrlen);

extern int connect(int fd, uint8_t* addr, int addrlen);

extern int sendto(int fd, uint8_t* buf, int n, int flags, uint8_t* addr, int addrlen);

extern int recvfrom(int fd, uint8_t* buf, int n, int flags, uint8_t* addr, int* addrlen);

extern int getpid(void);

extern int* __errno_location(void);

extern int putchar(int c);

int sys__o_trunc(void);

Array_byte str__int_to_bytes(Region r, int n);

int io__print_loop(Array_byte s, int i);

int io__print(Array_byte s);

Array_byte str__concat_all(Region r, Array_Array_byte parts);

int iouring__uring_close(iouring__Ring r, int fd);

int iouring__submit_read(iouring__Ring r, int fd, Array_byte buf, int offset, int id);

int sys__o_rdonly(void);

Array_byte str__c_str(Region r, Array_byte s);

int sys__o_creat(void);

int iouring_batch__write_temp(iouring__Ring ring, Array_byte path, Array_byte content);

int str__total_len(Array_Array_byte parts);

int str__copy_into(Array_byte dst, Array_byte src, int at);

int iouring__uring_open(iouring__Ring r, Array_byte path, int flags, int mode);

int str__digits_count(int n);

int iouring__uring_write(iouring__Ring r, int fd, Array_byte buf, int offset);

int sys__o_wronly(void);

int iouring__drop_Ring(iouring__Ring r);

iouring__Completion iouring__wait_one(iouring__Ring r);

int iouring__ring_failed(iouring__Ring r);

int iouring__flush(iouring__Ring r);

iouring__Ring iouring__ring_new(int entries);

int main(void);

int io__println(Array_byte s);

int sys__o_trunc(void) {
    return 512;
}

Array_byte str__int_to_bytes(Region r, int n) {
    int k_1 = str__digits_count(n);
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = k_1;
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_2 = _arr_6;
    int neg_3 = (n < 0);
    int tmp_7;
    if (neg_3) {
        tmp_7 = (0 - n);
    } else {
        tmp_7 = n;
    }
    int x_4 = tmp_7;
    int pos_5 = (k_1 - 1);
    int tmp_10;
    if ((x_4 == 0)) {
        Array_byte _a_8 = dst_2;
        int _i_9 = 0;
        if (ORTO_REGIONS[_a_8.slot].gen != _a_8.expected_gen) abort();
        if (_i_9 < 0 || _i_9 >= _a_8.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_8.slot].buffer + _a_8.offset))[_i_9] = ((uint8_t)(48));
        (void)(0);
        return dst_2;
        tmp_10 = 0;
    } else {
        tmp_10 = 0;
    }
    (void)(tmp_10);
    while ((x_4 > 0)) {
        Array_byte _a_11 = dst_2;
        int _i_12 = pos_5;
        if (ORTO_REGIONS[_a_11.slot].gen != _a_11.expected_gen) abort();
        if (_i_12 < 0 || _i_12 >= _a_11.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_11.slot].buffer + _a_11.offset))[_i_12] = ((uint8_t)((48 + (x_4 % 10))));
        (void)(0);
        x_4 = (x_4 / 10);
        (void)(0);
        pos_5 = (pos_5 - 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    int tmp_15;
    if (neg_3) {
        Array_byte _a_13 = dst_2;
        int _i_14 = 0;
        if (ORTO_REGIONS[_a_13.slot].gen != _a_13.expected_gen) abort();
        if (_i_14 < 0 || _i_14 >= _a_13.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_13.slot].buffer + _a_13.offset))[_i_14] = ((uint8_t)(45));
        (void)(0);
        tmp_15 = 0;
    } else {
        tmp_15 = 0;
    }
    (void)(tmp_15);
    return dst_2;
}

int io__print_loop(Array_byte s, int i) {
    int tmp_4;
    if ((i >= s.len)) {
        tmp_4 = 0;
    } else {
        Array_byte _a_1 = s;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        (void)(putchar(((int)(_idx_3))));
        tmp_4 = io__print_loop(s, (i + 1));
    }
    return tmp_4;
}

int io__print(Array_byte s) {
    return io__print_loop(s, 0);
}

Array_byte str__concat_all(Region r, Array_Array_byte parts) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = str__total_len(parts);
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_1 = _arr_6;
    int at_2 = 0;
    int i_3 = 0;
    while ((i_3 < parts.len)) {
        Array_Array_byte _a_7 = parts;
        int _i_8 = i_3;
        if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        Array_byte _idx_9 = ((Array_byte*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8];
        (void)(str__copy_into(dst_1, _idx_9, at_2));
        Array_Array_byte _a_10 = parts;
        int _i_11 = i_3;
        if (ORTO_REGIONS[_a_10.slot].gen != _a_10.expected_gen) abort();
        if (_i_11 < 0 || _i_11 >= _a_10.len) abort();
        Array_byte _idx_12 = ((Array_byte*)(ORTO_REGIONS[_a_10.slot].buffer + _a_10.offset))[_i_11];
        at_2 = (at_2 + (_idx_12).len);
        (void)(0);
        i_3 = (i_3 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return dst_1;
}

int iouring__uring_close(iouring__Ring r, int fd) {
    return orto_ring_close(r.handle, fd);
}

int iouring__submit_read(iouring__Ring r, int fd, Array_byte buf, int offset, int id) {
    Array_byte _a_1 = buf;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    return orto_ring_submit_read(r.handle, fd, _data_2, buf.len, offset, id);
}

int sys__o_rdonly(void) {
    return 0;
}

Array_byte str__c_str(Region r, Array_byte s) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = (s.len + 1);
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_1 = _arr_6;
    (void)(str__copy_into(dst_1, s, 0));
    Array_byte _a_7 = dst_1;
    int _lo_8 = 0;
    int _hi_9 = s.len;
    if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
    if (_lo_8 < 0 || _hi_9 < _lo_8 || _hi_9 > _a_7.len) abort();
    Array_byte _sl_10 = ((Array_byte){ .slot = _a_7.slot, .offset = _a_7.offset + _lo_8 * (int)sizeof(uint8_t), .len = _hi_9 - _lo_8, .expected_gen = _a_7.expected_gen });
    return _sl_10;
}

int sys__o_creat(void) {
    return 64;
}

int iouring_batch__write_temp(iouring__Ring ring, Array_byte path, Array_byte content) {
    int fd_1 = iouring__uring_open(ring, path, ((sys__o_wronly() + sys__o_creat()) + sys__o_trunc()), 420);
    int tmp_1;
    if ((fd_1 < 0)) {
        return 1;
        tmp_1 = 0;
    } else {
        tmp_1 = 0;
    }
    (void)(tmp_1);
    (void)(iouring__uring_write(ring, fd_1, content, 0));
    (void)(iouring__uring_close(ring, fd_1));
    return 0;
}

int str__total_len(Array_Array_byte parts) {
    int total_1 = 0;
    int i_2 = 0;
    while ((i_2 < parts.len)) {
        Array_Array_byte _a_1 = parts;
        int _i_2 = i_2;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        Array_byte _idx_3 = ((Array_byte*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        total_1 = (total_1 + (_idx_3).len);
        (void)(0);
        i_2 = (i_2 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return total_1;
}

int str__copy_into(Array_byte dst, Array_byte src, int at) {
    int i_1 = 0;
    while ((i_1 < src.len)) {
        Array_byte _a_3 = src;
        int _i_4 = i_1;
        if (ORTO_REGIONS[_a_3.slot].gen != _a_3.expected_gen) abort();
        if (_i_4 < 0 || _i_4 >= _a_3.len) abort();
        uint8_t _idx_5 = ((uint8_t*)(ORTO_REGIONS[_a_3.slot].buffer + _a_3.offset))[_i_4];
        Array_byte _a_1 = dst;
        int _i_2 = (at + i_1);
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = _idx_5;
        (void)(0);
        i_1 = (i_1 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return 0;
}

int iouring__uring_open(iouring__Ring r, Array_byte path, int flags, int mode) {
    Array_byte _a_1 = path;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    return orto_ring_openat(r.handle, _data_2, flags, mode);
}

int str__digits_count(int n) {
    int tmp_1;
    if ((n == 0)) {
        return 1;
        tmp_1 = 0;
    } else {
        tmp_1 = 0;
    }
    (void)(tmp_1);
    int count_1 = 0;
    int tmp_2;
    if ((n < 0)) {
        tmp_2 = (0 - n);
    } else {
        tmp_2 = n;
    }
    int x_2 = tmp_2;
    while ((x_2 > 0)) {
        count_1 = (count_1 + 1);
        (void)(0);
        x_2 = (x_2 / 10);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    int tmp_3;
    if ((n < 0)) {
        tmp_3 = (count_1 + 1);
    } else {
        tmp_3 = count_1;
    }
    return tmp_3;
}

int iouring__uring_write(iouring__Ring r, int fd, Array_byte buf, int offset) {
    Array_byte _a_1 = buf;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    uint8_t* _data_2 = (uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset);
    return orto_ring_write(r.handle, fd, _data_2, buf.len, offset);
}

int sys__o_wronly(void) {
    return 1;
}

int iouring__drop_Ring(iouring__Ring r) {
    (void)(orto_ring_exit(r.handle));
    return 0;
}

iouring__Completion iouring__wait_one(iouring__Ring r) {
    int* id_buf_1 = ((int*)malloc((size_t)(1) * sizeof(int)));
    int res_2 = orto_ring_wait_one(r.handle, id_buf_1);
    int* _a_1 = id_buf_1;
    int _i_2 = 0;
    int _idx_3 = _a_1[_i_2];
    int id_3 = _idx_3;
    (void)((free(id_buf_1), 0));
    return ((iouring__Completion){ .id = id_3, .res = res_2 });
}

int iouring__ring_failed(iouring__Ring r) {
    return ((r.handle) == NULL);
}

int iouring__flush(iouring__Ring r) {
    return orto_ring_flush(r.handle);
}

iouring__Ring iouring__ring_new(int entries) {
    return ((iouring__Ring){ .handle = orto_ring_create(entries) });
}

int main(void) {
    int _n_1 = 8192;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_1 = _reg_3;
    iouring__Ring ring_2 = iouring__ring_new(16);
    int tmp_4;
    if (iouring__ring_failed(ring_2)) {
        return 10;
        tmp_4 = 0;
    } else {
        tmp_4 = 0;
    }
    (void)(tmp_4);
    Array_byte p1_3 = str__c_str(r_1, ((Array_byte){ .slot = 0, .offset = 0, .len = 21, .expected_gen = 1 }));
    Array_byte p2_4 = str__c_str(r_1, ((Array_byte){ .slot = 0, .offset = 21, .len = 21, .expected_gen = 1 }));
    Array_byte p3_5 = str__c_str(r_1, ((Array_byte){ .slot = 0, .offset = 42, .len = 21, .expected_gen = 1 }));
    (void)(iouring_batch__write_temp(ring_2, p1_3, ((Array_byte){ .slot = 0, .offset = 63, .len = 3, .expected_gen = 1 })));
    (void)(iouring_batch__write_temp(ring_2, p2_4, ((Array_byte){ .slot = 0, .offset = 66, .len = 2, .expected_gen = 1 })));
    (void)(iouring_batch__write_temp(ring_2, p3_5, ((Array_byte){ .slot = 0, .offset = 68, .len = 4, .expected_gen = 1 })));
    int fd1_6 = iouring__uring_open(ring_2, p1_3, sys__o_rdonly(), 0);
    int fd2_7 = iouring__uring_open(ring_2, p2_4, sys__o_rdonly(), 0);
    int fd3_8 = iouring__uring_open(ring_2, p3_5, sys__o_rdonly(), 0);
    int tmp_5;
    if ((((fd1_6 < 0) || (fd2_7 < 0)) || (fd3_8 < 0))) {
        return 11;
        tmp_5 = 0;
    } else {
        tmp_5 = 0;
    }
    (void)(tmp_5);
    Region _r_6 = r_1;
    if (ORTO_REGIONS[_r_6.slot].gen != _r_6.expected_gen) abort();
    int _n_7 = 16;
    if (_n_7 < 0) abort();
    if (ORTO_REGIONS[_r_6.slot].used + (size_t)_n_7 * sizeof(uint8_t) > ORTO_REGIONS[_r_6.slot].buffer_size) abort();
    int _off_8 = (int)ORTO_REGIONS[_r_6.slot].used;
    ORTO_REGIONS[_r_6.slot].used += (size_t)_n_7 * sizeof(uint8_t);
    uint8_t* _slots_9 = (uint8_t*)(ORTO_REGIONS[_r_6.slot].buffer + _off_8);
    for (int _i_10 = 0; _i_10 < _n_7; _i_10++) _slots_9[_i_10] = ((uint8_t)(0));
    Array_byte _arr_11 = ((Array_byte){ .slot = _r_6.slot, .offset = _off_8, .len = _n_7, .expected_gen = _r_6.expected_gen });
    Array_byte buf1_9 = _arr_11;
    Region _r_12 = r_1;
    if (ORTO_REGIONS[_r_12.slot].gen != _r_12.expected_gen) abort();
    int _n_13 = 16;
    if (_n_13 < 0) abort();
    if (ORTO_REGIONS[_r_12.slot].used + (size_t)_n_13 * sizeof(uint8_t) > ORTO_REGIONS[_r_12.slot].buffer_size) abort();
    int _off_14 = (int)ORTO_REGIONS[_r_12.slot].used;
    ORTO_REGIONS[_r_12.slot].used += (size_t)_n_13 * sizeof(uint8_t);
    uint8_t* _slots_15 = (uint8_t*)(ORTO_REGIONS[_r_12.slot].buffer + _off_14);
    for (int _i_16 = 0; _i_16 < _n_13; _i_16++) _slots_15[_i_16] = ((uint8_t)(0));
    Array_byte _arr_17 = ((Array_byte){ .slot = _r_12.slot, .offset = _off_14, .len = _n_13, .expected_gen = _r_12.expected_gen });
    Array_byte buf2_10 = _arr_17;
    Region _r_18 = r_1;
    if (ORTO_REGIONS[_r_18.slot].gen != _r_18.expected_gen) abort();
    int _n_19 = 16;
    if (_n_19 < 0) abort();
    if (ORTO_REGIONS[_r_18.slot].used + (size_t)_n_19 * sizeof(uint8_t) > ORTO_REGIONS[_r_18.slot].buffer_size) abort();
    int _off_20 = (int)ORTO_REGIONS[_r_18.slot].used;
    ORTO_REGIONS[_r_18.slot].used += (size_t)_n_19 * sizeof(uint8_t);
    uint8_t* _slots_21 = (uint8_t*)(ORTO_REGIONS[_r_18.slot].buffer + _off_20);
    for (int _i_22 = 0; _i_22 < _n_19; _i_22++) _slots_21[_i_22] = ((uint8_t)(0));
    Array_byte _arr_23 = ((Array_byte){ .slot = _r_18.slot, .offset = _off_20, .len = _n_19, .expected_gen = _r_18.expected_gen });
    Array_byte buf3_11 = _arr_23;
    (void)(iouring__submit_read(ring_2, fd1_6, buf1_9, 0, 101));
    (void)(iouring__submit_read(ring_2, fd2_7, buf2_10, 0, 102));
    (void)(iouring__submit_read(ring_2, fd3_8, buf3_11, 0, 103));
    int submitted_12 = iouring__flush(ring_2);
    int tmp_24;
    if ((submitted_12 != 3)) {
        return 12;
        tmp_24 = 0;
    } else {
        tmp_24 = 0;
    }
    (void)(tmp_24);
    int completed_13 = 0;
    int total_bytes_14 = 0;
    while ((completed_13 < 3)) {
        iouring__Completion c_15 = iouring__wait_one(ring_2);
        int tmp_25;
        if ((c_15.res < 0)) {
            return 13;
            tmp_25 = 0;
        } else {
            tmp_25 = 0;
        }
        (void)(tmp_25);
        total_bytes_14 = (total_bytes_14 + c_15.res);
        (void)(0);
        completed_13 = (completed_13 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    (void)(iouring__uring_close(ring_2, fd1_6));
    (void)(iouring__uring_close(ring_2, fd2_7));
    (void)(iouring__uring_close(ring_2, fd3_8));
    Array_byte _a_26 = buf1_9;
    int _lo_27 = 0;
    int _hi_28 = 3;
    if (ORTO_REGIONS[_a_26.slot].gen != _a_26.expected_gen) abort();
    if (_lo_27 < 0 || _hi_28 < _lo_27 || _hi_28 > _a_26.len) abort();
    Array_byte _sl_29 = ((Array_byte){ .slot = _a_26.slot, .offset = _a_26.offset + _lo_27 * (int)sizeof(uint8_t), .len = _hi_28 - _lo_27, .expected_gen = _a_26.expected_gen });
    (void)(io__print(_sl_29));
    Array_byte _a_30 = buf2_10;
    int _lo_31 = 0;
    int _hi_32 = 2;
    if (ORTO_REGIONS[_a_30.slot].gen != _a_30.expected_gen) abort();
    if (_lo_31 < 0 || _hi_32 < _lo_31 || _hi_32 > _a_30.len) abort();
    Array_byte _sl_33 = ((Array_byte){ .slot = _a_30.slot, .offset = _a_30.offset + _lo_31 * (int)sizeof(uint8_t), .len = _hi_32 - _lo_31, .expected_gen = _a_30.expected_gen });
    (void)(io__print(_sl_33));
    Array_byte _a_34 = buf3_11;
    int _lo_35 = 0;
    int _hi_36 = 4;
    if (ORTO_REGIONS[_a_34.slot].gen != _a_34.expected_gen) abort();
    if (_lo_35 < 0 || _hi_36 < _lo_35 || _hi_36 > _a_34.len) abort();
    Array_byte _sl_37 = ((Array_byte){ .slot = _a_34.slot, .offset = _a_34.offset + _lo_35 * (int)sizeof(uint8_t), .len = _hi_36 - _lo_35, .expected_gen = _a_34.expected_gen });
    (void)(io__print(_sl_37));
    Region _r_38 = r_1;
    if (ORTO_REGIONS[_r_38.slot].gen != _r_38.expected_gen) abort();
    if (ORTO_REGIONS[_r_38.slot].used + (size_t)5 * sizeof(Array_byte) > ORTO_REGIONS[_r_38.slot].buffer_size) abort();
    int _off_39 = (int)ORTO_REGIONS[_r_38.slot].used;
    ORTO_REGIONS[_r_38.slot].used += (size_t)5 * sizeof(Array_byte);
    Array_byte* _slots_40 = (Array_byte*)(ORTO_REGIONS[_r_38.slot].buffer + _off_39);
    _slots_40[0] = ((Array_byte){ .slot = 0, .offset = 72, .len = 16, .expected_gen = 1 });
    _slots_40[1] = str__int_to_bytes(r_1, completed_13);
    _slots_40[2] = ((Array_byte){ .slot = 0, .offset = 88, .len = 6, .expected_gen = 1 });
    _slots_40[3] = str__int_to_bytes(r_1, total_bytes_14);
    _slots_40[4] = ((Array_byte){ .slot = 0, .offset = 94, .len = 24, .expected_gen = 1 });
    Array_Array_byte _arr_41 = ((Array_Array_byte){ .slot = _r_38.slot, .offset = _off_39, .len = 5, .expected_gen = _r_38.expected_gen });
    (void)(io__println(str__concat_all(r_1, _arr_41)));
    int _let_result_42 = 0;
    iouring__drop_Ring(ring_2);
    int _let_result_43 = _let_result_42;
    drop_Region(r_1);
    return _let_result_43;
}

int io__println(Array_byte s) {
    (void)(io__print_loop(s, 0));
    return putchar(10);
}