/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct linear_basic__Socket linear_basic__Socket;

typedef int (*fn_int_to_int)(int);

typedef linear_basic__Socket (*fn_to_linear_basic__Socket)(void);

typedef int (*fn_linear_basic__Socket_to_int)(linear_basic__Socket);

struct linear_basic__Socket {
    int fd;
};

extern int putchar(int c);

linear_basic__Socket linear_basic__open_fake(void);

int linear_basic__drop_Socket(linear_basic__Socket s);

int linear_basic__use_socket(linear_basic__Socket s);

int main(void);

linear_basic__Socket linear_basic__open_fake(void) {
    return ((linear_basic__Socket){ .fd = 7 });
}

int linear_basic__drop_Socket(linear_basic__Socket s) {
    (void)(putchar(68));
    (void)(putchar(((10 + s.fd) - s.fd)));
    return 0;
}

int linear_basic__use_socket(linear_basic__Socket s) {
    (void)(putchar(85));
    (void)(putchar((48 + s.fd)));
    (void)(putchar(10));
    return 0;
}

int main(void) {
    linear_basic__Socket s_1 = linear_basic__open_fake();
    (void)(linear_basic__use_socket(s_1));
    (void)(linear_basic__use_socket(s_1));
    int _let_result_1 = 0;
    linear_basic__drop_Socket(s_1);
    return _let_result_1;
}