/* generated by orto */
#include <stdlib.h>

typedef struct List_int List_int;

typedef struct Option_List_int Option_List_int;

struct Ref_List_int_cell;

typedef struct { struct Ref_List_int_cell* ptr; int expected_gen; } Ref_List_int;

typedef int (*fn_List_int_to_int)(List_int);

struct List_int {
    int tag;
    union {
        struct { int f0; Ref_List_int f1; } Cons;
    } as;
};

struct Option_List_int {
    int tag;
    union {
        struct { List_int f0; } Some;
    } as;
};

struct Ref_List_int_cell { int gen; List_int value; };

int length(List_int xs);

int sum(List_int xs);

int main(void);

int length(List_int xs) {
    List_int scrut_1 = xs;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Nil */
            match_result_2 = 0;
            break;
        }
        case 1: { /* Cons */
            Ref_List_int rest_1 = scrut_1.as.Cons.f1;
            Ref_List_int _r_4 = rest_1;
            Option_List_int _deref_3;
            if (_r_4.ptr->gen == _r_4.expected_gen) {
                _deref_3 = (Option_List_int){ .tag = 0, .as = { .Some = { .f0 = _r_4.ptr->value } } };
            } else {
                _deref_3 = (Option_List_int){ .tag = 1 };
            }
            Option_List_int scrut_5 = _deref_3;
            List_int match_result_6;
            switch (scrut_5.tag) {
                case 0: { /* Some */
                    List_int _qq_v_2 = scrut_5.as.Some.f0;
                    match_result_6 = _qq_v_2;
                    break;
                }
                case 1: { /* None */
                    match_result_6 = ((List_int){ .tag = 0 });
                    break;
                }
                default: abort();
            }
            match_result_2 = (1 + length(match_result_6));
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int sum(List_int xs) {
    List_int scrut_1 = xs;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Nil */
            match_result_2 = 0;
            break;
        }
        case 1: { /* Cons */
            int h_1 = scrut_1.as.Cons.f0;
            Ref_List_int rest_2 = scrut_1.as.Cons.f1;
            Ref_List_int _r_4 = rest_2;
            Option_List_int _deref_3;
            if (_r_4.ptr->gen == _r_4.expected_gen) {
                _deref_3 = (Option_List_int){ .tag = 0, .as = { .Some = { .f0 = _r_4.ptr->value } } };
            } else {
                _deref_3 = (Option_List_int){ .tag = 1 };
            }
            Option_List_int scrut_5 = _deref_3;
            List_int match_result_6;
            switch (scrut_5.tag) {
                case 0: { /* Some */
                    List_int _qq_v_3 = scrut_5.as.Some.f0;
                    match_result_6 = _qq_v_3;
                    break;
                }
                case 1: { /* None */
                    match_result_6 = ((List_int){ .tag = 0 });
                    break;
                }
                default: abort();
            }
            match_result_2 = (h_1 + sum(match_result_6));
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int main(void) {
    struct Ref_List_int_cell* _cell_1 = malloc(sizeof(struct Ref_List_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = ((List_int){ .tag = 0 });
    Ref_List_int tail0_1 = ((Ref_List_int){ .ptr = _cell_1, .expected_gen = 1 });
    List_int l1_2 = ((List_int){ .tag = 1, .as = { .Cons = { .f0 = 4, .f1 = tail0_1 } } });
    struct Ref_List_int_cell* _cell_2 = malloc(sizeof(struct Ref_List_int_cell));
    if (!_cell_2) abort();
    _cell_2->gen = 1;
    _cell_2->value = l1_2;
    Ref_List_int tail1_3 = ((Ref_List_int){ .ptr = _cell_2, .expected_gen = 1 });
    List_int l2_4 = ((List_int){ .tag = 1, .as = { .Cons = { .f0 = 3, .f1 = tail1_3 } } });
    struct Ref_List_int_cell* _cell_3 = malloc(sizeof(struct Ref_List_int_cell));
    if (!_cell_3) abort();
    _cell_3->gen = 1;
    _cell_3->value = l2_4;
    Ref_List_int tail2_5 = ((Ref_List_int){ .ptr = _cell_3, .expected_gen = 1 });
    List_int l3_6 = ((List_int){ .tag = 1, .as = { .Cons = { .f0 = 2, .f1 = tail2_5 } } });
    struct Ref_List_int_cell* _cell_4 = malloc(sizeof(struct Ref_List_int_cell));
    if (!_cell_4) abort();
    _cell_4->gen = 1;
    _cell_4->value = l3_6;
    Ref_List_int tail3_7 = ((Ref_List_int){ .ptr = _cell_4, .expected_gen = 1 });
    List_int xs_8 = ((List_int){ .tag = 1, .as = { .Cons = { .f0 = 1, .f1 = tail3_7 } } });
    return (length(xs_8) + sum(xs_8));
}