/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[56] = { 0x75, 0x73, 0x65, 0x72, 0x61, 0x67, 0x65, 0x63, 0x69, 0x74, 0x79, 0x3e, 0x3e, 0x20, 0x20, 0x28, 0x29, 0x20, 0x6c, 0x69, 0x76, 0x65, 0x73, 0x20, 0x69, 0x6e, 0x20, 0x20, 0x3c, 0x3c, 0x75, 0x73, 0x65, 0x72, 0x3d, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2c, 0x61, 0x67, 0x65, 0x3d, 0x33, 0x30, 0x2c, 0x63, 0x69, 0x74, 0x79, 0x3d, 0x4e, 0x59, 0x43 };
#define ORTO_STATIC_BYTES_LEN 56

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_Array_byte;

typedef Array_byte (*fn_Region_Array_byte_to_Array_byte)(Region, Array_byte);

typedef Array_byte (*fn_Array_byte_Array_byte_to_Array_byte)(Array_byte, Array_byte);

typedef Array_byte (*fn_Region_int_to_Array_byte)(Region, int);

typedef int (*fn_Array_byte_to_int)(Array_byte);

typedef Array_byte (*fn_Region_Array_Array_byte_to_Array_byte)(Region, Array_Array_byte);

typedef int (*fn_int_to_int)(int);

typedef int (*fn_Array_byte_int_to_int)(Array_byte, int);

typedef int (*fn_Array_byte_Array_byte_to_bool)(Array_byte, Array_byte);

typedef int (*fn_Array_byte_byte_to_int)(Array_byte, uint8_t);

typedef int (*fn_Array_Array_byte_to_int)(Array_Array_byte);

typedef int (*fn_Array_byte_Array_byte_int_to_int)(Array_byte, Array_byte, int);

typedef uint8_t (*fn_byte_to_byte)(uint8_t);

extern int putchar(int c);

Array_byte log_format__format_log(Region r, Array_byte input);

int io__print_loop(Array_byte s, int i);

Array_byte str__int_to_bytes(Region r, int n);

Array_byte str__lookup(Array_byte s, Array_byte key);

int str__bytes_eq(Array_byte a, Array_byte b);

Array_byte str__concat_all(Region r, Array_Array_byte parts);

int str__index_of(Array_byte s, uint8_t c);

uint8_t str__upper_byte(uint8_t b);

int str__total_len(Array_Array_byte parts);

Array_byte str__to_upper(Region r, Array_byte s);

int str__copy_into(Array_byte dst, Array_byte src, int at);

int str__parse_int(Array_byte s);

int str__digits_count(int n);

int main(void);

int io__println(Array_byte s);

Array_byte log_format__format_log(Region r, Array_byte input) {
    Array_byte name_1 = str__to_upper(r, str__lookup(input, ((Array_byte){ .slot = 0, .offset = 0, .len = 4, .expected_gen = 1 })));
    Array_byte age_2 = str__int_to_bytes(r, str__parse_int(str__lookup(input, ((Array_byte){ .slot = 0, .offset = 4, .len = 3, .expected_gen = 1 }))));
    Array_byte city_3 = str__lookup(input, ((Array_byte){ .slot = 0, .offset = 7, .len = 4, .expected_gen = 1 }));
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)7 * sizeof(Array_byte) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_2 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)7 * sizeof(Array_byte);
    Array_byte* _slots_3 = (Array_byte*)(ORTO_REGIONS[_r_1.slot].buffer + _off_2);
    _slots_3[0] = ((Array_byte){ .slot = 0, .offset = 11, .len = 3, .expected_gen = 1 });
    _slots_3[1] = name_1;
    _slots_3[2] = ((Array_byte){ .slot = 0, .offset = 14, .len = 2, .expected_gen = 1 });
    _slots_3[3] = age_2;
    _slots_3[4] = ((Array_byte){ .slot = 0, .offset = 16, .len = 11, .expected_gen = 1 });
    _slots_3[5] = city_3;
    _slots_3[6] = ((Array_byte){ .slot = 0, .offset = 27, .len = 3, .expected_gen = 1 });
    Array_Array_byte _arr_4 = ((Array_Array_byte){ .slot = _r_1.slot, .offset = _off_2, .len = 7, .expected_gen = _r_1.expected_gen });
    return str__concat_all(r, _arr_4);
}

int io__print_loop(Array_byte s, int i) {
    int tmp_4;
    if ((i >= s.len)) {
        tmp_4 = 0;
    } else {
        Array_byte _a_1 = s;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        (void)(putchar(((int)(_idx_3))));
        tmp_4 = io__print_loop(s, (i + 1));
    }
    return tmp_4;
}

Array_byte str__int_to_bytes(Region r, int n) {
    int k_1 = str__digits_count(n);
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = k_1;
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_2 = _arr_6;
    int pos_3 = (k_1 - 1);
    int x_4 = n;
    while ((pos_3 >= 0)) {
        Array_byte _a_7 = dst_2;
        int _i_8 = pos_3;
        if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8] = ((uint8_t)((48 + (x_4 % 10))));
        (void)(0);
        x_4 = (x_4 / 10);
        (void)(0);
        pos_3 = (pos_3 - 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return dst_2;
}

Array_byte str__lookup(Array_byte s, Array_byte key) {
    int from_1 = 0;
    while ((from_1 < s.len)) {
        Array_byte _a_1 = s;
        int _lo_2 = from_1;
        int _hi_3 = (from_1 + key.len);
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_lo_2 < 0 || _hi_3 < _lo_2 || _hi_3 > _a_1.len) abort();
        Array_byte _sl_4 = ((Array_byte){ .slot = _a_1.slot, .offset = _a_1.offset + _lo_2 * (int)sizeof(uint8_t), .len = _hi_3 - _lo_2, .expected_gen = _a_1.expected_gen });
        Array_byte _a_5 = s;
        int _i_6 = (from_1 + key.len);
        if (ORTO_REGIONS[_a_5.slot].gen != _a_5.expected_gen) abort();
        if (_i_6 < 0 || _i_6 >= _a_5.len) abort();
        uint8_t _idx_7 = ((uint8_t*)(ORTO_REGIONS[_a_5.slot].buffer + _a_5.offset))[_i_6];
        int tmp_17;
        if ((((((from_1 + key.len) + 1) <= s.len) && str__bytes_eq(_sl_4, key)) && (_idx_7 == ((uint8_t)(61))))) {
            int val_start_2 = ((from_1 + key.len) + 1);
            Array_byte _a_8 = s;
            int _lo_9 = val_start_2;
            int _hi_10 = s.len;
            if (ORTO_REGIONS[_a_8.slot].gen != _a_8.expected_gen) abort();
            if (_lo_9 < 0 || _hi_10 < _lo_9 || _hi_10 > _a_8.len) abort();
            Array_byte _sl_11 = ((Array_byte){ .slot = _a_8.slot, .offset = _a_8.offset + _lo_9 * (int)sizeof(uint8_t), .len = _hi_10 - _lo_9, .expected_gen = _a_8.expected_gen });
            Array_byte rest_3 = _sl_11;
            int comma_4 = str__index_of(rest_3, ((uint8_t)(44)));
            Array_byte tmp_16;
            if ((comma_4 < 0)) {
                tmp_16 = rest_3;
            } else {
                Array_byte _a_12 = rest_3;
                int _lo_13 = 0;
                int _hi_14 = comma_4;
                if (ORTO_REGIONS[_a_12.slot].gen != _a_12.expected_gen) abort();
                if (_lo_13 < 0 || _hi_14 < _lo_13 || _hi_14 > _a_12.len) abort();
                Array_byte _sl_15 = ((Array_byte){ .slot = _a_12.slot, .offset = _a_12.offset + _lo_13 * (int)sizeof(uint8_t), .len = _hi_14 - _lo_13, .expected_gen = _a_12.expected_gen });
                tmp_16 = _sl_15;
            }
            return tmp_16;
            tmp_17 = 0;
        } else {
            tmp_17 = 0;
        }
        (void)(tmp_17);
        Array_byte _a_18 = s;
        int _lo_19 = from_1;
        int _hi_20 = s.len;
        if (ORTO_REGIONS[_a_18.slot].gen != _a_18.expected_gen) abort();
        if (_lo_19 < 0 || _hi_20 < _lo_19 || _hi_20 > _a_18.len) abort();
        Array_byte _sl_21 = ((Array_byte){ .slot = _a_18.slot, .offset = _a_18.offset + _lo_19 * (int)sizeof(uint8_t), .len = _hi_20 - _lo_19, .expected_gen = _a_18.expected_gen });
        Array_byte rest_5 = _sl_21;
        int comma_6 = str__index_of(rest_5, ((uint8_t)(44)));
        int tmp_26;
        if ((comma_6 < 0)) {
            Array_byte _a_22 = s;
            int _lo_23 = 0;
            int _hi_24 = 0;
            if (ORTO_REGIONS[_a_22.slot].gen != _a_22.expected_gen) abort();
            if (_lo_23 < 0 || _hi_24 < _lo_23 || _hi_24 > _a_22.len) abort();
            Array_byte _sl_25 = ((Array_byte){ .slot = _a_22.slot, .offset = _a_22.offset + _lo_23 * (int)sizeof(uint8_t), .len = _hi_24 - _lo_23, .expected_gen = _a_22.expected_gen });
            return _sl_25;
            tmp_26 = 0;
        } else {
            tmp_26 = 0;
        }
        (void)(tmp_26);
        from_1 = ((from_1 + comma_6) + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    Array_byte _a_27 = s;
    int _lo_28 = 0;
    int _hi_29 = 0;
    if (ORTO_REGIONS[_a_27.slot].gen != _a_27.expected_gen) abort();
    if (_lo_28 < 0 || _hi_29 < _lo_28 || _hi_29 > _a_27.len) abort();
    Array_byte _sl_30 = ((Array_byte){ .slot = _a_27.slot, .offset = _a_27.offset + _lo_28 * (int)sizeof(uint8_t), .len = _hi_29 - _lo_28, .expected_gen = _a_27.expected_gen });
    return _sl_30;
}

int str__bytes_eq(Array_byte a, Array_byte b) {
    int tmp_8;
    if ((a.len != b.len)) {
        tmp_8 = 0;
    } else {
        int i_1 = 0;
        while ((i_1 < a.len)) {
            Array_byte _a_1 = a;
            int _i_2 = i_1;
            if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
            if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
            uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
            Array_byte _a_4 = b;
            int _i_5 = i_1;
            if (ORTO_REGIONS[_a_4.slot].gen != _a_4.expected_gen) abort();
            if (_i_5 < 0 || _i_5 >= _a_4.len) abort();
            uint8_t _idx_6 = ((uint8_t*)(ORTO_REGIONS[_a_4.slot].buffer + _a_4.offset))[_i_5];
            int tmp_7;
            if ((_idx_3 != _idx_6)) {
                break;
                tmp_7 = 0;
            } else {
                tmp_7 = 0;
            }
            (void)(tmp_7);
            i_1 = (i_1 + 1);
            (void)(0);
            (void)(0);
        }
        (void)(0);
        tmp_8 = (i_1 == a.len);
    }
    return tmp_8;
}

Array_byte str__concat_all(Region r, Array_Array_byte parts) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = str__total_len(parts);
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_1 = _arr_6;
    int at_2 = 0;
    int i_3 = 0;
    while ((i_3 < parts.len)) {
        Array_Array_byte _a_7 = parts;
        int _i_8 = i_3;
        if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        Array_byte _idx_9 = ((Array_byte*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8];
        (void)(str__copy_into(dst_1, _idx_9, at_2));
        Array_Array_byte _a_10 = parts;
        int _i_11 = i_3;
        if (ORTO_REGIONS[_a_10.slot].gen != _a_10.expected_gen) abort();
        if (_i_11 < 0 || _i_11 >= _a_10.len) abort();
        Array_byte _idx_12 = ((Array_byte*)(ORTO_REGIONS[_a_10.slot].buffer + _a_10.offset))[_i_11];
        at_2 = (at_2 + (_idx_12).len);
        (void)(0);
        i_3 = (i_3 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return dst_1;
}

int str__index_of(Array_byte s, uint8_t c) {
    int i_1 = 0;
    while ((i_1 < s.len)) {
        Array_byte _a_1 = s;
        int _i_2 = i_1;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        int tmp_4;
        if ((_idx_3 == c)) {
            break;
            tmp_4 = 0;
        } else {
            tmp_4 = 0;
        }
        (void)(tmp_4);
        i_1 = (i_1 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    int tmp_5;
    if ((i_1 == s.len)) {
        tmp_5 = (0 - 1);
    } else {
        tmp_5 = i_1;
    }
    return tmp_5;
}

uint8_t str__upper_byte(uint8_t b) {
    int n_1 = ((int)(b));
    uint8_t tmp_1;
    if (((n_1 >= 97) && (n_1 <= 122))) {
        tmp_1 = ((uint8_t)((n_1 - 32)));
    } else {
        tmp_1 = b;
    }
    return tmp_1;
}

int str__total_len(Array_Array_byte parts) {
    int total_1 = 0;
    int i_2 = 0;
    while ((i_2 < parts.len)) {
        Array_Array_byte _a_1 = parts;
        int _i_2 = i_2;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        Array_byte _idx_3 = ((Array_byte*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        total_1 = (total_1 + (_idx_3).len);
        (void)(0);
        i_2 = (i_2 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return total_1;
}

Array_byte str__to_upper(Region r, Array_byte s) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = s.len;
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_1 = _arr_6;
    int i_2 = 0;
    while ((i_2 < s.len)) {
        Array_byte _a_9 = s;
        int _i_10 = i_2;
        if (ORTO_REGIONS[_a_9.slot].gen != _a_9.expected_gen) abort();
        if (_i_10 < 0 || _i_10 >= _a_9.len) abort();
        uint8_t _idx_11 = ((uint8_t*)(ORTO_REGIONS[_a_9.slot].buffer + _a_9.offset))[_i_10];
        Array_byte _a_7 = dst_1;
        int _i_8 = i_2;
        if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8] = str__upper_byte(_idx_11);
        (void)(0);
        i_2 = (i_2 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return dst_1;
}

int str__copy_into(Array_byte dst, Array_byte src, int at) {
    int i_1 = 0;
    while ((i_1 < src.len)) {
        Array_byte _a_3 = src;
        int _i_4 = i_1;
        if (ORTO_REGIONS[_a_3.slot].gen != _a_3.expected_gen) abort();
        if (_i_4 < 0 || _i_4 >= _a_3.len) abort();
        uint8_t _idx_5 = ((uint8_t*)(ORTO_REGIONS[_a_3.slot].buffer + _a_3.offset))[_i_4];
        Array_byte _a_1 = dst;
        int _i_2 = (at + i_1);
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = _idx_5;
        (void)(0);
        i_1 = (i_1 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return 0;
}

int str__parse_int(Array_byte s) {
    int acc_1 = 0;
    int i_2 = 0;
    while ((i_2 < s.len)) {
        Array_byte _a_1 = s;
        int _i_2 = i_2;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        int n_3 = ((int)(_idx_3));
        int tmp_4;
        if (((n_3 < 48) || (n_3 > 57))) {
            break;
            tmp_4 = 0;
        } else {
            tmp_4 = 0;
        }
        (void)(tmp_4);
        acc_1 = ((acc_1 * 10) + (n_3 - 48));
        (void)(0);
        i_2 = (i_2 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return acc_1;
}

int str__digits_count(int n) {
    int count_1 = 1;
    int x_2 = (n / 10);
    while ((x_2 > 0)) {
        count_1 = (count_1 + 1);
        (void)(0);
        x_2 = (x_2 / 10);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return count_1;
}

int main(void) {
    int _n_1 = 4096;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_1 = _reg_3;
    Array_byte line_2 = log_format__format_log(r_1, ((Array_byte){ .slot = 0, .offset = 30, .len = 26, .expected_gen = 1 }));
    (void)(io__println(line_2));
    int _let_result_4 = line_2.len;
    drop_Region(r_1);
    return _let_result_4;
}

int io__println(Array_byte s) {
    (void)(io__print_loop(s, 0));
    return putchar(10);
}