/* generated by orto */
#include <stdlib.h>

typedef struct Option_int Option_int;

struct Ref_int_cell;

typedef struct { struct Ref_int_cell* ptr; int expected_gen; } Ref_int;

typedef int (*fn_Ref_int_int_to_int)(Ref_int, int);

struct Option_int {
    int tag;
    union {
        struct { int f0; } Some;
    } as;
};

struct Ref_int_cell { int gen; int value; };

int bump(Ref_int r, int by);

int main(void);

int bump(Ref_int r, int by) {
    Ref_int _r_2 = r;
    Option_int _deref_1;
    if (_r_2.ptr->gen == _r_2.expected_gen) {
        _deref_1 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_2.ptr->value } } };
    } else {
        _deref_1 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_3 = _deref_1;
    int match_result_4;
    switch (scrut_3.tag) {
        case 0: { /* Some */
            int _qq_v_1 = scrut_3.as.Some.f0;
            match_result_4 = _qq_v_1;
            break;
        }
        case 1: { /* None */
            match_result_4 = 0;
            break;
        }
        default: abort();
    }
    int cur_2 = match_result_4;
    Ref_int _r_6 = r;
    int _v_7 = (cur_2 + by);
    Option_int _assign_5;
    if (_r_6.ptr->gen == _r_6.expected_gen) {
        _r_6.ptr->value = _v_7;
        _assign_5 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _v_7 } } };
    } else {
        _assign_5 = (Option_int){ .tag = 1 };
    }
    (void)(_assign_5);
    return (cur_2 + by);
}

int main(void) {
    struct Ref_int_cell* _cell_1 = malloc(sizeof(struct Ref_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 100;
    Ref_int counter_1 = ((Ref_int){ .ptr = _cell_1, .expected_gen = 1 });
    (void)(bump(counter_1, 5));
    (void)(bump(counter_1, 10));
    (void)(bump(counter_1, 20));
    Ref_int _r_3 = counter_1;
    Option_int _deref_2;
    if (_r_3.ptr->gen == _r_3.expected_gen) {
        _deref_2 = (Option_int){ .tag = 0, .as = { .Some = { .f0 = _r_3.ptr->value } } };
    } else {
        _deref_2 = (Option_int){ .tag = 1 };
    }
    Option_int scrut_4 = _deref_2;
    int match_result_5;
    switch (scrut_4.tag) {
        case 0: { /* Some */
            int _qq_v_2 = scrut_4.as.Some.f0;
            match_result_5 = _qq_v_2;
            break;
        }
        case 1: { /* None */
            abort();
            int _panic_6 = (int){0};
            match_result_5 = _panic_6;
            break;
        }
        default: abort();
    }
    return match_result_5;
}