/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[41] = { 0x4e, 0x6c, 0x4d, 0x73, 0x67, 0x48, 0x64, 0x72, 0x20, 0x7b, 0x20, 0x6c, 0x65, 0x6e, 0x3d, 0x20, 0x74, 0x79, 0x70, 0x65, 0x3d, 0x20, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x3d, 0x20, 0x73, 0x65, 0x71, 0x3d, 0x20, 0x70, 0x69, 0x64, 0x3d, 0x20, 0x7d, 0x0a };
#define ORTO_STATIC_BYTES_LEN 41

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct netlink_msg__NlMsgHdr netlink_msg__NlMsgHdr;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_Array_byte;

typedef int (*fn_int_to_int)(int);

typedef int (*fn_Array_byte_int_to_int)(Array_byte, int);

typedef int (*fn_Array_Array_byte_to_int)(Array_Array_byte);

typedef int (*fn_Array_byte_Array_byte_int_to_int)(Array_byte, Array_byte, int);

typedef Array_byte (*fn_Region_Array_Array_byte_to_Array_byte)(Region, Array_Array_byte);

typedef Array_byte (*fn_Region_int_to_Array_byte)(Region, int);

typedef Array_byte (*fn_Region_netlink_msg__NlMsgHdr_to_Array_byte)(Region, netlink_msg__NlMsgHdr);

typedef netlink_msg__NlMsgHdr (*fn_Array_byte_to_netlink_msg__NlMsgHdr)(Array_byte);

typedef int (*fn_Array_byte_to_int)(Array_byte);

typedef int (*fn_Array_byte_int_int_to_int)(Array_byte, int, int);

struct netlink_msg__NlMsgHdr {
    int length;
    int type_;
    int flags;
    int seq;
    int pid;
};

extern int putchar(int c);

int bin__read_u16_le(Array_byte buf, int off);

Array_byte str__int_to_bytes(Region r, int n);

int io__print_loop(Array_byte s, int i);

int bin__read_u32_le(Array_byte buf, int off);

Array_byte str__concat_all(Region r, Array_Array_byte parts);

int bin__write_u16_le(Array_byte buf, int off, int v);

int str__total_len(Array_Array_byte parts);

int str__copy_into(Array_byte dst, Array_byte src, int at);

int str__digits_count(int n);

netlink_msg__NlMsgHdr netlink_msg__nl_hdr_parse(Array_byte buf);

Array_byte netlink_msg__nl_hdr_show(Region r, netlink_msg__NlMsgHdr h);

int bin__write_u32_le(Array_byte buf, int off, int v);

int main(void);

int io__println(Array_byte s);

Array_byte netlink_msg__nl_hdr_serialize(Region r, netlink_msg__NlMsgHdr h);

int bin__read_u16_le(Array_byte buf, int off) {
    Array_byte _a_1 = buf;
    int _i_2 = off;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
    uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
    Array_byte _a_4 = buf;
    int _i_5 = (off + 1);
    if (ORTO_REGIONS[_a_4.slot].gen != _a_4.expected_gen) abort();
    if (_i_5 < 0 || _i_5 >= _a_4.len) abort();
    uint8_t _idx_6 = ((uint8_t*)(ORTO_REGIONS[_a_4.slot].buffer + _a_4.offset))[_i_5];
    return (((int)(_idx_3)) + (((int)(_idx_6)) * 256));
}

Array_byte str__int_to_bytes(Region r, int n) {
    int k_1 = str__digits_count(n);
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = k_1;
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_2 = _arr_6;
    int neg_3 = (n < 0);
    int tmp_7;
    if (neg_3) {
        tmp_7 = (0 - n);
    } else {
        tmp_7 = n;
    }
    int x_4 = tmp_7;
    int pos_5 = (k_1 - 1);
    int tmp_10;
    if ((x_4 == 0)) {
        Array_byte _a_8 = dst_2;
        int _i_9 = 0;
        if (ORTO_REGIONS[_a_8.slot].gen != _a_8.expected_gen) abort();
        if (_i_9 < 0 || _i_9 >= _a_8.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_8.slot].buffer + _a_8.offset))[_i_9] = ((uint8_t)(48));
        (void)(0);
        return dst_2;
        tmp_10 = 0;
    } else {
        tmp_10 = 0;
    }
    (void)(tmp_10);
    while ((x_4 > 0)) {
        Array_byte _a_11 = dst_2;
        int _i_12 = pos_5;
        if (ORTO_REGIONS[_a_11.slot].gen != _a_11.expected_gen) abort();
        if (_i_12 < 0 || _i_12 >= _a_11.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_11.slot].buffer + _a_11.offset))[_i_12] = ((uint8_t)((48 + (x_4 % 10))));
        (void)(0);
        x_4 = (x_4 / 10);
        (void)(0);
        pos_5 = (pos_5 - 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    int tmp_15;
    if (neg_3) {
        Array_byte _a_13 = dst_2;
        int _i_14 = 0;
        if (ORTO_REGIONS[_a_13.slot].gen != _a_13.expected_gen) abort();
        if (_i_14 < 0 || _i_14 >= _a_13.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_13.slot].buffer + _a_13.offset))[_i_14] = ((uint8_t)(45));
        (void)(0);
        tmp_15 = 0;
    } else {
        tmp_15 = 0;
    }
    (void)(tmp_15);
    return dst_2;
}

int io__print_loop(Array_byte s, int i) {
    int tmp_4;
    if ((i >= s.len)) {
        tmp_4 = 0;
    } else {
        Array_byte _a_1 = s;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        (void)(putchar(((int)(_idx_3))));
        tmp_4 = io__print_loop(s, (i + 1));
    }
    return tmp_4;
}

int bin__read_u32_le(Array_byte buf, int off) {
    Array_byte _a_1 = buf;
    int _i_2 = off;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
    uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
    Array_byte _a_4 = buf;
    int _i_5 = (off + 1);
    if (ORTO_REGIONS[_a_4.slot].gen != _a_4.expected_gen) abort();
    if (_i_5 < 0 || _i_5 >= _a_4.len) abort();
    uint8_t _idx_6 = ((uint8_t*)(ORTO_REGIONS[_a_4.slot].buffer + _a_4.offset))[_i_5];
    Array_byte _a_7 = buf;
    int _i_8 = (off + 2);
    if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
    if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
    uint8_t _idx_9 = ((uint8_t*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8];
    Array_byte _a_10 = buf;
    int _i_11 = (off + 3);
    if (ORTO_REGIONS[_a_10.slot].gen != _a_10.expected_gen) abort();
    if (_i_11 < 0 || _i_11 >= _a_10.len) abort();
    uint8_t _idx_12 = ((uint8_t*)(ORTO_REGIONS[_a_10.slot].buffer + _a_10.offset))[_i_11];
    return (((((int)(_idx_3)) + (((int)(_idx_6)) * 256)) + (((int)(_idx_9)) * 65536)) + (((int)(_idx_12)) * 16777216));
}

Array_byte str__concat_all(Region r, Array_Array_byte parts) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = str__total_len(parts);
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte dst_1 = _arr_6;
    int at_2 = 0;
    int i_3 = 0;
    while ((i_3 < parts.len)) {
        Array_Array_byte _a_7 = parts;
        int _i_8 = i_3;
        if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
        if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
        Array_byte _idx_9 = ((Array_byte*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8];
        (void)(str__copy_into(dst_1, _idx_9, at_2));
        Array_Array_byte _a_10 = parts;
        int _i_11 = i_3;
        if (ORTO_REGIONS[_a_10.slot].gen != _a_10.expected_gen) abort();
        if (_i_11 < 0 || _i_11 >= _a_10.len) abort();
        Array_byte _idx_12 = ((Array_byte*)(ORTO_REGIONS[_a_10.slot].buffer + _a_10.offset))[_i_11];
        at_2 = (at_2 + (_idx_12).len);
        (void)(0);
        i_3 = (i_3 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return dst_1;
}

int bin__write_u16_le(Array_byte buf, int off, int v) {
    Array_byte _a_1 = buf;
    int _i_2 = off;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
    ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = ((uint8_t)((v % 256)));
    (void)(0);
    Array_byte _a_3 = buf;
    int _i_4 = (off + 1);
    if (ORTO_REGIONS[_a_3.slot].gen != _a_3.expected_gen) abort();
    if (_i_4 < 0 || _i_4 >= _a_3.len) abort();
    ((uint8_t*)(ORTO_REGIONS[_a_3.slot].buffer + _a_3.offset))[_i_4] = ((uint8_t)(((v / 256) % 256)));
    (void)(0);
    return 0;
}

int str__total_len(Array_Array_byte parts) {
    int total_1 = 0;
    int i_2 = 0;
    while ((i_2 < parts.len)) {
        Array_Array_byte _a_1 = parts;
        int _i_2 = i_2;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        Array_byte _idx_3 = ((Array_byte*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        total_1 = (total_1 + (_idx_3).len);
        (void)(0);
        i_2 = (i_2 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return total_1;
}

int str__copy_into(Array_byte dst, Array_byte src, int at) {
    int i_1 = 0;
    while ((i_1 < src.len)) {
        Array_byte _a_3 = src;
        int _i_4 = i_1;
        if (ORTO_REGIONS[_a_3.slot].gen != _a_3.expected_gen) abort();
        if (_i_4 < 0 || _i_4 >= _a_3.len) abort();
        uint8_t _idx_5 = ((uint8_t*)(ORTO_REGIONS[_a_3.slot].buffer + _a_3.offset))[_i_4];
        Array_byte _a_1 = dst;
        int _i_2 = (at + i_1);
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = _idx_5;
        (void)(0);
        i_1 = (i_1 + 1);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    return 0;
}

int str__digits_count(int n) {
    int tmp_1;
    if ((n == 0)) {
        return 1;
        tmp_1 = 0;
    } else {
        tmp_1 = 0;
    }
    (void)(tmp_1);
    int count_1 = 0;
    int tmp_2;
    if ((n < 0)) {
        tmp_2 = (0 - n);
    } else {
        tmp_2 = n;
    }
    int x_2 = tmp_2;
    while ((x_2 > 0)) {
        count_1 = (count_1 + 1);
        (void)(0);
        x_2 = (x_2 / 10);
        (void)(0);
        (void)(0);
    }
    (void)(0);
    int tmp_3;
    if ((n < 0)) {
        tmp_3 = (count_1 + 1);
    } else {
        tmp_3 = count_1;
    }
    return tmp_3;
}

netlink_msg__NlMsgHdr netlink_msg__nl_hdr_parse(Array_byte buf) {
    return ((netlink_msg__NlMsgHdr){ .length = bin__read_u32_le(buf, 0), .type_ = bin__read_u16_le(buf, 4), .flags = bin__read_u16_le(buf, 6), .seq = bin__read_u32_le(buf, 8), .pid = bin__read_u32_le(buf, 12) });
}

Array_byte netlink_msg__nl_hdr_show(Region r, netlink_msg__NlMsgHdr h) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)11 * sizeof(Array_byte) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_2 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)11 * sizeof(Array_byte);
    Array_byte* _slots_3 = (Array_byte*)(ORTO_REGIONS[_r_1.slot].buffer + _off_2);
    _slots_3[0] = ((Array_byte){ .slot = 0, .offset = 0, .len = 15, .expected_gen = 1 });
    _slots_3[1] = str__int_to_bytes(r, h.length);
    _slots_3[2] = ((Array_byte){ .slot = 0, .offset = 15, .len = 6, .expected_gen = 1 });
    _slots_3[3] = str__int_to_bytes(r, h.type_);
    _slots_3[4] = ((Array_byte){ .slot = 0, .offset = 21, .len = 7, .expected_gen = 1 });
    _slots_3[5] = str__int_to_bytes(r, h.flags);
    _slots_3[6] = ((Array_byte){ .slot = 0, .offset = 28, .len = 5, .expected_gen = 1 });
    _slots_3[7] = str__int_to_bytes(r, h.seq);
    _slots_3[8] = ((Array_byte){ .slot = 0, .offset = 33, .len = 5, .expected_gen = 1 });
    _slots_3[9] = str__int_to_bytes(r, h.pid);
    _slots_3[10] = ((Array_byte){ .slot = 0, .offset = 38, .len = 3, .expected_gen = 1 });
    Array_Array_byte _arr_4 = ((Array_Array_byte){ .slot = _r_1.slot, .offset = _off_2, .len = 11, .expected_gen = _r_1.expected_gen });
    return str__concat_all(r, _arr_4);
}

int bin__write_u32_le(Array_byte buf, int off, int v) {
    Array_byte _a_1 = buf;
    int _i_2 = off;
    if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
    if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
    ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = ((uint8_t)((v % 256)));
    (void)(0);
    Array_byte _a_3 = buf;
    int _i_4 = (off + 1);
    if (ORTO_REGIONS[_a_3.slot].gen != _a_3.expected_gen) abort();
    if (_i_4 < 0 || _i_4 >= _a_3.len) abort();
    ((uint8_t*)(ORTO_REGIONS[_a_3.slot].buffer + _a_3.offset))[_i_4] = ((uint8_t)(((v / 256) % 256)));
    (void)(0);
    Array_byte _a_5 = buf;
    int _i_6 = (off + 2);
    if (ORTO_REGIONS[_a_5.slot].gen != _a_5.expected_gen) abort();
    if (_i_6 < 0 || _i_6 >= _a_5.len) abort();
    ((uint8_t*)(ORTO_REGIONS[_a_5.slot].buffer + _a_5.offset))[_i_6] = ((uint8_t)(((v / 65536) % 256)));
    (void)(0);
    Array_byte _a_7 = buf;
    int _i_8 = (off + 3);
    if (ORTO_REGIONS[_a_7.slot].gen != _a_7.expected_gen) abort();
    if (_i_8 < 0 || _i_8 >= _a_7.len) abort();
    ((uint8_t*)(ORTO_REGIONS[_a_7.slot].buffer + _a_7.offset))[_i_8] = ((uint8_t)(((v / 16777216) % 256)));
    (void)(0);
    return 0;
}

int main(void) {
    int _n_1 = 4096;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_1 = _reg_3;
    netlink_msg__NlMsgHdr req_2 = ((netlink_msg__NlMsgHdr){ .length = 32, .type_ = 18, .flags = 769, .seq = 42, .pid = 0 });
    Array_byte bytes_3 = netlink_msg__nl_hdr_serialize(r_1, req_2);
    int tmp_4;
    if ((bytes_3.len != 16)) {
        return 1;
        tmp_4 = 0;
    } else {
        tmp_4 = 0;
    }
    (void)(tmp_4);
    netlink_msg__NlMsgHdr parsed_4 = netlink_msg__nl_hdr_parse(bytes_3);
    int tmp_5;
    if ((parsed_4.length != 32)) {
        return 2;
        tmp_5 = 0;
    } else {
        tmp_5 = 0;
    }
    (void)(tmp_5);
    int tmp_6;
    if ((parsed_4.type_ != 18)) {
        return 3;
        tmp_6 = 0;
    } else {
        tmp_6 = 0;
    }
    (void)(tmp_6);
    int tmp_7;
    if ((parsed_4.flags != 769)) {
        return 4;
        tmp_7 = 0;
    } else {
        tmp_7 = 0;
    }
    (void)(tmp_7);
    int tmp_8;
    if ((parsed_4.seq != 42)) {
        return 5;
        tmp_8 = 0;
    } else {
        tmp_8 = 0;
    }
    (void)(tmp_8);
    int tmp_9;
    if ((parsed_4.pid != 0)) {
        return 6;
        tmp_9 = 0;
    } else {
        tmp_9 = 0;
    }
    (void)(tmp_9);
    (void)(io__println(netlink_msg__nl_hdr_show(r_1, parsed_4)));
    int _let_result_10 = 0;
    drop_Region(r_1);
    return _let_result_10;
}

int io__println(Array_byte s) {
    (void)(io__print_loop(s, 0));
    return putchar(10);
}

Array_byte netlink_msg__nl_hdr_serialize(Region r, netlink_msg__NlMsgHdr h) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    int _n_2 = 16;
    if (_n_2 < 0) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)_n_2 * sizeof(uint8_t) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_3 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)_n_2 * sizeof(uint8_t);
    uint8_t* _slots_4 = (uint8_t*)(ORTO_REGIONS[_r_1.slot].buffer + _off_3);
    for (int _i_5 = 0; _i_5 < _n_2; _i_5++) _slots_4[_i_5] = ((uint8_t)(0));
    Array_byte _arr_6 = ((Array_byte){ .slot = _r_1.slot, .offset = _off_3, .len = _n_2, .expected_gen = _r_1.expected_gen });
    Array_byte buf_1 = _arr_6;
    (void)(bin__write_u32_le(buf_1, 0, h.length));
    (void)(bin__write_u16_le(buf_1, 4, h.type_));
    (void)(bin__write_u16_le(buf_1, 6, h.flags));
    (void)(bin__write_u32_le(buf_1, 8, h.seq));
    (void)(bin__write_u32_le(buf_1, 12, h.pid));
    return buf_1;
}