/* generated by orto */
#include <stdlib.h>

int main(void);

int main(void) {
    int a_1 = (2 + (3 * 4));
    int b_2 = ((2 + 3) * 4);
    int c_3 = ((10 - 3) - 2);
    int d_4 = (17 % 5);
    int e_5 = (100 / 7);
    int f_6 = ((-8) + 10);
    int cond_7 = (((a_1 > 10) && (b_2 < 100)) || (c_3 == 5));
    int tmp_1;
    if (cond_7) {
        tmp_1 = (a_1 + b_2);
    } else {
        tmp_1 = (a_1 - b_2);
    }
    int g_8 = tmp_1;
    int tmp_2;
    if ((!cond_7)) {
        tmp_2 = 0;
    } else {
        tmp_2 = 1;
    }
    int h_9 = tmp_2;
    int tmp_3;
    if ((d_4 != e_5)) {
        tmp_3 = 1;
    } else {
        tmp_3 = 0;
    }
    int k_10 = tmp_3;
    int tmp_4;
    if ((e_5 >= 14)) {
        tmp_4 = 7;
    } else {
        tmp_4 = 0;
    }
    int l_11 = tmp_4;
    return (((((((((a_1 + b_2) + c_3) + d_4) + e_5) + f_6) + g_8) + h_9) + k_10) + l_11);
}