/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

int main(void);

int main(void) {
    int a_1 = (2 + (3 * 4));
    int b_2 = ((2 + 3) * 4);
    int c_3 = ((10 - 3) - 2);
    int d_4 = (17 % 5);
    int e_5 = (100 / 7);
    int f_6 = ((-8) + 10);
    int cond_7 = (((a_1 > 10) && (b_2 < 100)) || (c_3 == 5));
    int tmp_1;
    if (cond_7) {
        tmp_1 = (a_1 + b_2);
    } else {
        tmp_1 = (a_1 - b_2);
    }
    int g_8 = tmp_1;
    int tmp_2;
    if ((!cond_7)) {
        tmp_2 = 0;
    } else {
        tmp_2 = 1;
    }
    int h_9 = tmp_2;
    int tmp_3;
    if ((d_4 != e_5)) {
        tmp_3 = 1;
    } else {
        tmp_3 = 0;
    }
    int k_10 = tmp_3;
    int tmp_4;
    if ((e_5 >= 14)) {
        tmp_4 = 7;
    } else {
        tmp_4 = 0;
    }
    int l_11 = tmp_4;
    return (((((((((a_1 + b_2) + c_3) + d_4) + e_5) + f_6) + g_8) + h_9) + k_10) + l_11);
}