/* generated by orto */
#include <stdlib.h>

struct Own_int_cell;

typedef struct { struct Own_int_cell* ptr; int expected_gen; } Own_int;

struct Own_int_cell { int gen; int value; };

int main(void);

int main(void) {
    struct Own_int_cell* _cell_1 = malloc(sizeof(struct Own_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 7;
    Own_int x_1 = ((Own_int){ .ptr = _cell_1, .expected_gen = 1 });
    Own_int _o_2 = x_1;
    if (_o_2.ptr->gen != _o_2.expected_gen) abort();
    int _unwrap_3 = _o_2.ptr->value;
    free(_o_2.ptr);
    int tmp_4;
    if ((_unwrap_3 > 5)) {
        tmp_4 = 100;
    } else {
        tmp_4 = 200;
    }
    int result_2 = tmp_4;
    return result_2;
}