/* generated by orto */
#include <stdlib.h>

struct Own_int_cell;

typedef struct { struct Own_int_cell* ptr; int expected_gen; } Own_int;

struct Own_int_cell { int gen; int value; };

int main(void);

int main(void) {
    struct Own_int_cell* _cell_1 = malloc(sizeof(struct Own_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 5;
    Own_int a_1 = ((Own_int){ .ptr = _cell_1, .expected_gen = 1 });
    struct Own_int_cell* _cell_2 = malloc(sizeof(struct Own_int_cell));
    if (!_cell_2) abort();
    _cell_2->gen = 1;
    _cell_2->value = 10;
    Own_int b_2 = ((Own_int){ .ptr = _cell_2, .expected_gen = 1 });
    Own_int _o_3 = a_1;
    if (_o_3.ptr->gen != _o_3.expected_gen) abort();
    int _unwrap_4 = _o_3.ptr->value;
    free(_o_3.ptr);
    Own_int _o_5 = b_2;
    if (_o_5.ptr->gen != _o_5.expected_gen) abort();
    int _unwrap_6 = _o_5.ptr->value;
    free(_o_5.ptr);
    int sum_3 = (_unwrap_4 + _unwrap_6);
    struct Own_int_cell* _cell_7 = malloc(sizeof(struct Own_int_cell));
    if (!_cell_7) abort();
    _cell_7->gen = 1;
    _cell_7->value = 2;
    Own_int factor_4 = ((Own_int){ .ptr = _cell_7, .expected_gen = 1 });
    Own_int _o_8 = factor_4;
    if (_o_8.ptr->gen != _o_8.expected_gen) abort();
    int _unwrap_9 = _o_8.ptr->value;
    free(_o_8.ptr);
    int result_5 = (sum_3 * _unwrap_9);
    return result_5;
}