/* generated by orto */
#include <stdlib.h>

struct Own_int_cell;

typedef struct { struct Own_int_cell* ptr; int expected_gen; } Own_int;

typedef int (*fn_to_int)(void);

struct Own_int_cell { int gen; int value; };

int produce(void);

int main(void);

int produce(void) {
    struct Own_int_cell* _cell_1 = malloc(sizeof(struct Own_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 77;
    Own_int x_1 = ((Own_int){ .ptr = _cell_1, .expected_gen = 1 });
    Own_int y_2 = x_1;
    Own_int _o_2 = y_2;
    if (_o_2.ptr->gen != _o_2.expected_gen) abort();
    int _unwrap_3 = _o_2.ptr->value;
    free(_o_2.ptr);
    return _unwrap_3;
}

int main(void) {
    return produce();
}