/* generated by orto */
#include <stdlib.h>

struct Own_int_cell;

typedef struct { struct Own_int_cell* ptr; int expected_gen; } Own_int;

struct Own_int_cell { int gen; int value; };

int main(void);

int main(void) {
    struct Own_int_cell* _cell_1 = malloc(sizeof(struct Own_int_cell));
    if (!_cell_1) abort();
    _cell_1->gen = 1;
    _cell_1->value = 5;
    Own_int x_1 = ((Own_int){ .ptr = _cell_1, .expected_gen = 1 });
    Own_int _o_2 = x_1;
    if (_o_2.ptr->gen != _o_2.expected_gen) abort();
    int _unwrap_3 = _o_2.ptr->value;
    int v_2 = _unwrap_3;
    int _let_result_4 = v_2;
    free(x_1.ptr);
    return _let_result_4;
}