/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef int (*fn_int_to_int)(int);

typedef int (*fn_bool_to_bool)(int);

int poly_id__id_bool(int x);

int poly_id__id_int(int x);

int main(void);

int poly_id__id_bool(int x) {
    return x;
}

int poly_id__id_int(int x) {
    return x;
}

int main(void) {
    int a_1 = poly_id__id_int(7);
    int b_2 = poly_id__id_bool(1);
    int tmp_1;
    if (b_2) {
        tmp_1 = (a_1 + 35);
    } else {
        tmp_1 = 0;
    }
    return tmp_1;
}