/* generated by orto */
#include <stdlib.h>

typedef int (*fn_int_to_int)(int);

typedef int (*fn_bool_to_bool)(int);

int id_bool(int x);

int id_int(int x);

int main(void);

int id_bool(int x) {
    return x;
}

int id_int(int x) {
    return x;
}

int main(void) {
    int a_1 = id_int(7);
    int b_2 = id_bool(1);
    int tmp_1;
    if (b_2) {
        tmp_1 = (a_1 + 35);
    } else {
        tmp_1 = 0;
    }
    return tmp_1;
}