/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct Option_int Option_int;

typedef struct poly_adt__Pair_int_bool poly_adt__Pair_int_bool;

typedef int (*fn_Option_int_int_to_int)(Option_int, int);

typedef int (*fn_poly_adt__Pair_int_bool_to_int)(poly_adt__Pair_int_bool);

typedef int (*fn_poly_adt__Pair_int_bool_to_bool)(poly_adt__Pair_int_bool);

struct Option_int {
    int tag;
    union {
        struct { int f0; } Some;
    } as;
};

struct poly_adt__Pair_int_bool {
    int tag;
    union {
        struct { int f0; int f1; } poly_adt__MkPair;
    } as;
};

int poly_adt__snd_int_bool(poly_adt__Pair_int_bool p);

int poly_adt__or_default_int(Option_int o, int def);

int poly_adt__fst_int_bool(poly_adt__Pair_int_bool p);

int main(void);

int poly_adt__snd_int_bool(poly_adt__Pair_int_bool p) {
    poly_adt__Pair_int_bool scrut_1 = p;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* poly_adt__MkPair */
            int b_1 = scrut_1.as.poly_adt__MkPair.f1;
            match_result_2 = b_1;
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int poly_adt__or_default_int(Option_int o, int def) {
    Option_int scrut_1 = o;
    int match_result_2;
    switch (scrut_1.tag) {
        case 1: { /* None */
            match_result_2 = def;
            break;
        }
        case 0: { /* Some */
            int x_1 = scrut_1.as.Some.f0;
            match_result_2 = x_1;
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int poly_adt__fst_int_bool(poly_adt__Pair_int_bool p) {
    poly_adt__Pair_int_bool scrut_1 = p;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* poly_adt__MkPair */
            int a_1 = scrut_1.as.poly_adt__MkPair.f0;
            match_result_2 = a_1;
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int main(void) {
    Option_int a_1 = ((Option_int){ .tag = 0, .as = { .Some = { .f0 = 7 } } });
    Option_int b_2 = ((Option_int){ .tag = 1 });
    poly_adt__Pair_int_bool p_3 = ((poly_adt__Pair_int_bool){ .tag = 0, .as = { .poly_adt__MkPair = { .f0 = 110, .f1 = 1 } } });
    int v1_4 = poly_adt__or_default_int(a_1, 0);
    int v2_5 = poly_adt__or_default_int(b_2, 0);
    int v3_6 = poly_adt__fst_int_bool(p_3);
    int tmp_1;
    if (poly_adt__snd_int_bool(p_3)) {
        tmp_1 = 0;
    } else {
        tmp_1 = 99;
    }
    int v4_7 = tmp_1;
    return (((v1_4 + v2_5) + v3_6) + v4_7);
}