/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[3] = { 0x68, 0x69, 0x0a };
#define ORTO_STATIC_BYTES_LEN 3

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef int (*fn_ptr_int_int_int_to_int)(int*, int, int);

typedef int (*fn_int_ptr_byte_int_to_int)(int, uint8_t*, int);

extern int putchar(int c);

extern int write(int fd, uint8_t* buf, int n);

int raw_pointers__fill(int* p, int i, int n);

int raw_pointers__sum(int* p, int i, int n);

int main(void);

int raw_pointers__fill(int* p, int i, int n) {
    int tmp_3;
    if ((i >= n)) {
        tmp_3 = 0;
    } else {
        int* _a_1 = p;
        int _i_2 = i;
        _a_1[_i_2] = (i * i);
        (void)(0);
        tmp_3 = raw_pointers__fill(p, (i + 1), n);
    }
    return tmp_3;
}

int raw_pointers__sum(int* p, int i, int n) {
    int tmp_4;
    if ((i >= n)) {
        tmp_4 = 0;
    } else {
        int* _a_1 = p;
        int _i_2 = i;
        int _idx_3 = _a_1[_i_2];
        tmp_4 = (_idx_3 + raw_pointers__sum(p, (i + 1), n));
    }
    return tmp_4;
}

int main(void) {
    int* buf_1 = ((int*)malloc((size_t)(5) * sizeof(int)));
    (void)(raw_pointers__fill(buf_1, 0, 5));
    int total_2 = raw_pointers__sum(buf_1, 0, 5);
    int first_3 = (*buf_1);
    (void)((free(buf_1), 0));
    int* p_4 = ((int*)NULL);
    int tmp_1;
    if (((p_4) == NULL)) {
        tmp_1 = 1;
    } else {
        tmp_1 = 0;
    }
    int nullness_5 = tmp_1;
    Array_byte _a_2 = ((Array_byte){ .slot = 0, .offset = 0, .len = 3, .expected_gen = 1 });
    if (ORTO_REGIONS[_a_2.slot].gen != _a_2.expected_gen) abort();
    uint8_t* _data_3 = (uint8_t*)(ORTO_REGIONS[_a_2.slot].buffer + _a_2.offset);
    (void)(write(1, _data_3, 3));
    return ((total_2 + first_3) + nullness_5);
}