/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct Result_Pair_int_int Result_Pair_int_int;

typedef struct Pair_int_int Pair_int_int;

typedef struct Point Point;

typedef struct Pair_int_bool Pair_int_bool;

typedef struct Pair_bool_int Pair_bool_int;

typedef struct Bag Bag;

typedef int (*fn_Point_to_int)(Point);

typedef Pair_bool_int (*fn_Pair_int_bool_to_Pair_bool_int)(Pair_int_bool);

typedef int (*fn_Result_Pair_int_int_to_int)(Result_Pair_int_int);

struct Point {
    int x;
    int y;
};

struct Pair_int_int {
    int fst;
    int snd;
};

struct Result_Pair_int_int {
    int tag;
    union {
        struct { Pair_int_int f0; } Ok;
        struct { Point f0; } Err;
    } as;
};

struct Pair_int_bool {
    int fst;
    int snd;
};

struct Pair_bool_int {
    int fst;
    int snd;
};

struct Bag {
    int count;
    int flag;
};

int pick(Result_Pair_int_int r);

Pair_bool_int swap_int_bool(Pair_int_bool p);

int dist_sq(Point p);

int main(void);

int pick(Result_Pair_int_int r) {
    Result_Pair_int_int scrut_1 = r;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Ok */
            Pair_int_int p_1 = scrut_1.as.Ok.f0;
            match_result_2 = (p_1.fst + p_1.snd);
            break;
        }
        case 1: { /* Err */
            Point q_2 = scrut_1.as.Err.f0;
            match_result_2 = (q_2.x + q_2.y);
            break;
        }
        default: abort();
    }
    return match_result_2;
}

Pair_bool_int swap_int_bool(Pair_int_bool p) {
    return ((Pair_bool_int){ .fst = p.snd, .snd = p.fst });
}

int dist_sq(Point p) {
    return ((p.x * p.x) + (p.y * p.y));
}

int main(void) {
    Point p_1 = ((Point){ .x = 3, .y = 4 });
    int d_2 = dist_sq(p_1);
    Pair_int_bool pq_3 = ((Pair_int_bool){ .fst = 7, .snd = 1 });
    Pair_bool_int sw_4 = swap_int_bool(pq_3);
    int tmp_1;
    if (sw_4.fst) {
        tmp_1 = sw_4.snd;
    } else {
        tmp_1 = 0;
    }
    int a_5 = tmp_1;
    Result_Pair_int_int r1_6 = ((Result_Pair_int_int){ .tag = 0, .as = { .Ok = { .f0 = ((Pair_int_int){ .fst = 10, .snd = 20 }) } } });
    Result_Pair_int_int r2_7 = ((Result_Pair_int_int){ .tag = 1, .as = { .Err = { .f0 = ((Point){ .x = 1, .y = 2 }) } } });
    int b_8 = pick(r1_6);
    int c_9 = pick(r2_7);
    Bag bag_10 = ((Bag){ .count = 8, .flag = 0 });
    int tmp_2;
    if (bag_10.flag) {
        tmp_2 = 100;
    } else {
        tmp_2 = bag_10.count;
    }
    int e_11 = tmp_2;
    return ((((d_2 + a_5) + b_8) + c_9) + e_11);
}