/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct records__Result_records__Pair_int_int records__Result_records__Pair_int_int;

typedef struct records__Pair_int_int records__Pair_int_int;

typedef struct records__Bag records__Bag;

typedef struct records__Pair_bool_int records__Pair_bool_int;

typedef struct records__Pair_int_bool records__Pair_int_bool;

typedef struct records__Point records__Point;

typedef int (*fn_records__Point_to_int)(records__Point);

typedef records__Pair_bool_int (*fn_records__Pair_int_bool_to_records__Pair_bool_int)(records__Pair_int_bool);

typedef int (*fn_records__Result_records__Pair_int_int_to_int)(records__Result_records__Pair_int_int);

struct records__Point {
    int x;
    int y;
};

struct records__Pair_int_int {
    int fst;
    int snd;
};

struct records__Result_records__Pair_int_int {
    int tag;
    union {
        struct { records__Pair_int_int f0; } records__Ok;
        struct { records__Point f0; } records__Err;
    } as;
};

struct records__Bag {
    int count;
    int flag;
};

struct records__Pair_bool_int {
    int fst;
    int snd;
};

struct records__Pair_int_bool {
    int fst;
    int snd;
};

int records__dist_sq(records__Point p);

records__Pair_bool_int records__swap_int_bool(records__Pair_int_bool p);

int main(void);

int records__pick(records__Result_records__Pair_int_int r);

int records__dist_sq(records__Point p) {
    return ((p.x * p.x) + (p.y * p.y));
}

records__Pair_bool_int records__swap_int_bool(records__Pair_int_bool p) {
    return ((records__Pair_bool_int){ .fst = p.snd, .snd = p.fst });
}

int main(void) {
    records__Point p_1 = ((records__Point){ .x = 3, .y = 4 });
    int d_2 = records__dist_sq(p_1);
    records__Pair_int_bool pq_3 = ((records__Pair_int_bool){ .fst = 7, .snd = 1 });
    records__Pair_bool_int sw_4 = records__swap_int_bool(pq_3);
    int tmp_1;
    if (sw_4.fst) {
        tmp_1 = sw_4.snd;
    } else {
        tmp_1 = 0;
    }
    int a_5 = tmp_1;
    records__Result_records__Pair_int_int r1_6 = ((records__Result_records__Pair_int_int){ .tag = 0, .as = { .records__Ok = { .f0 = ((records__Pair_int_int){ .fst = 10, .snd = 20 }) } } });
    records__Result_records__Pair_int_int r2_7 = ((records__Result_records__Pair_int_int){ .tag = 1, .as = { .records__Err = { .f0 = ((records__Point){ .x = 1, .y = 2 }) } } });
    int b_8 = records__pick(r1_6);
    int c_9 = records__pick(r2_7);
    records__Bag bag_10 = ((records__Bag){ .count = 8, .flag = 0 });
    int tmp_2;
    if (bag_10.flag) {
        tmp_2 = 100;
    } else {
        tmp_2 = bag_10.count;
    }
    int e_11 = tmp_2;
    return ((((d_2 + a_5) + b_8) + c_9) + e_11);
}

int records__pick(records__Result_records__Pair_int_int r) {
    records__Result_records__Pair_int_int scrut_1 = r;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* records__Ok */
            records__Pair_int_int p_1 = scrut_1.as.records__Ok.f0;
            match_result_2 = (p_1.fst + p_1.snd);
            break;
        }
        case 1: { /* records__Err */
            records__Point q_2 = scrut_1.as.records__Err.f0;
            match_result_2 = (q_2.x + q_2.y);
            break;
        }
        default: abort();
    }
    return match_result_2;
}