/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
typedef struct { int slot; int expected_gen; } Region;
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static void drop_Region(Region r) {
    if (ORTO_REGIONS[r.slot].gen != r.expected_gen) return;
    if (!ORTO_REGIONS[r.slot].is_stack)
        free(ORTO_REGIONS[r.slot].buffer);
    ORTO_REGIONS[r.slot].buffer = NULL;
    ORTO_REGIONS[r.slot].buffer_size = 0;
    ORTO_REGIONS[r.slot].used = 0;
    ORTO_REGIONS[r.slot].gen++;
    ORTO_REGIONS[r.slot].next_free = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = r.slot;
}

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}

typedef struct region_as_file__Connection region_as_file__Connection;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_int;

typedef int (*fn_int_to_int)(int);

typedef region_as_file__Connection (*fn_int_to_region_as_file__Connection)(int);

typedef int (*fn_region_as_file__Connection_int_to_int)(region_as_file__Connection, int);

typedef int (*fn_Region_to_int)(Region);

struct region_as_file__Connection {
    int fd;
};

extern int putchar(int c);

int region_as_file__allocate_some(Region r);

int region_as_file__drop_Connection(region_as_file__Connection c);

region_as_file__Connection region_as_file__open_db(int host);

int region_as_file__query(region_as_file__Connection c, int q);

int main(void);

int region_as_file__allocate_some(Region r) {
    Region _r_1 = r;
    if (ORTO_REGIONS[_r_1.slot].gen != _r_1.expected_gen) abort();
    if (ORTO_REGIONS[_r_1.slot].used + (size_t)3 * sizeof(int) > ORTO_REGIONS[_r_1.slot].buffer_size) abort();
    int _off_2 = (int)ORTO_REGIONS[_r_1.slot].used;
    ORTO_REGIONS[_r_1.slot].used += (size_t)3 * sizeof(int);
    int* _slots_3 = (int*)(ORTO_REGIONS[_r_1.slot].buffer + _off_2);
    _slots_3[0] = 10;
    _slots_3[1] = 20;
    _slots_3[2] = 30;
    Array_int _arr_4 = ((Array_int){ .slot = _r_1.slot, .offset = _off_2, .len = 3, .expected_gen = _r_1.expected_gen });
    Array_int a_1 = _arr_4;
    Array_int _a_5 = a_1;
    int _i_6 = 0;
    if (ORTO_REGIONS[_a_5.slot].gen != _a_5.expected_gen) abort();
    if (_i_6 < 0 || _i_6 >= _a_5.len) abort();
    int _idx_7 = ((int*)(ORTO_REGIONS[_a_5.slot].buffer + _a_5.offset))[_i_6];
    Array_int _a_8 = a_1;
    int _i_9 = 1;
    if (ORTO_REGIONS[_a_8.slot].gen != _a_8.expected_gen) abort();
    if (_i_9 < 0 || _i_9 >= _a_8.len) abort();
    int _idx_10 = ((int*)(ORTO_REGIONS[_a_8.slot].buffer + _a_8.offset))[_i_9];
    Array_int _a_11 = a_1;
    int _i_12 = 2;
    if (ORTO_REGIONS[_a_11.slot].gen != _a_11.expected_gen) abort();
    if (_i_12 < 0 || _i_12 >= _a_11.len) abort();
    int _idx_13 = ((int*)(ORTO_REGIONS[_a_11.slot].buffer + _a_11.offset))[_i_12];
    return ((_idx_7 + _idx_10) + _idx_13);
}

int region_as_file__drop_Connection(region_as_file__Connection c) {
    (void)(putchar(67));
    (void)(putchar(10));
    return 0;
}

region_as_file__Connection region_as_file__open_db(int host) {
    return ((region_as_file__Connection){ .fd = host });
}

int region_as_file__query(region_as_file__Connection c, int q) {
    (void)(putchar(81));
    (void)(putchar((48 + c.fd)));
    (void)(putchar((48 + q)));
    (void)(putchar(10));
    return 0;
}

int main(void) {
    region_as_file__Connection c_1 = region_as_file__open_db(7);
    (void)(region_as_file__query(c_1, 1));
    (void)(region_as_file__query(c_1, 2));
    int _n_1 = 1024;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_2 = _reg_3;
    int sum1_3 = region_as_file__allocate_some(r_2);
    int sum2_4 = region_as_file__allocate_some(r_2);
    int _let_result_4 = ((sum1_3 + sum2_4) + 0);
    drop_Region(r_2);
    int _let_result_5 = _let_result_4;
    region_as_file__drop_Connection(c_1);
    return _let_result_5;
}