/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_int;

int main(void);

int main(void) {
    int _n_1 = 4096;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region heap_1 = _reg_3;
    Region _r_4 = heap_1;
    if (ORTO_REGIONS[_r_4.slot].gen != _r_4.expected_gen) abort();
    if (ORTO_REGIONS[_r_4.slot].used + (size_t)5 * sizeof(int) > ORTO_REGIONS[_r_4.slot].buffer_size) abort();
    int _off_5 = (int)ORTO_REGIONS[_r_4.slot].used;
    ORTO_REGIONS[_r_4.slot].used += (size_t)5 * sizeof(int);
    int* _slots_6 = (int*)(ORTO_REGIONS[_r_4.slot].buffer + _off_5);
    _slots_6[0] = 1;
    _slots_6[1] = 2;
    _slots_6[2] = 3;
    _slots_6[3] = 4;
    _slots_6[4] = 5;
    Array_int _arr_7 = ((Array_int){ .slot = _r_4.slot, .offset = _off_5, .len = 5, .expected_gen = _r_4.expected_gen });
    Array_int a_2 = _arr_7;
    char _stack_buf_8[1024];
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_9 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_9].next_free;
    ORTO_REGIONS[_slot_9].buffer = _stack_buf_8;
    ORTO_REGIONS[_slot_9].buffer_size = 1024;
    ORTO_REGIONS[_slot_9].used = 0;
    ORTO_REGIONS[_slot_9].next_free = -1;
    ORTO_REGIONS[_slot_9].is_stack = 1;
    Region _reg_10 = ((Region){ .slot = _slot_9, .expected_gen = ORTO_REGIONS[_slot_9].gen });
    Region stk_3 = _reg_10;
    Region _r_11 = stk_3;
    if (ORTO_REGIONS[_r_11.slot].gen != _r_11.expected_gen) abort();
    if (ORTO_REGIONS[_r_11.slot].used + (size_t)3 * sizeof(int) > ORTO_REGIONS[_r_11.slot].buffer_size) abort();
    int _off_12 = (int)ORTO_REGIONS[_r_11.slot].used;
    ORTO_REGIONS[_r_11.slot].used += (size_t)3 * sizeof(int);
    int* _slots_13 = (int*)(ORTO_REGIONS[_r_11.slot].buffer + _off_12);
    _slots_13[0] = 10;
    _slots_13[1] = 20;
    _slots_13[2] = 30;
    Array_int _arr_14 = ((Array_int){ .slot = _r_11.slot, .offset = _off_12, .len = 3, .expected_gen = _r_11.expected_gen });
    Array_int b_4 = _arr_14;
    int _n_15 = 4096;
    if (_n_15 < 0) abort();
    int _a_16 = 4096;
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_17 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_17].next_free;
    void* _buf_18 = NULL;
    if (posix_memalign(&_buf_18, (size_t)_a_16, (size_t)_n_15) != 0) abort();
    ORTO_REGIONS[_slot_17].buffer = (char*)_buf_18;
    ORTO_REGIONS[_slot_17].buffer_size = (size_t)_n_15;
    ORTO_REGIONS[_slot_17].used = 0;
    ORTO_REGIONS[_slot_17].next_free = -1;
    ORTO_REGIONS[_slot_17].is_stack = 0;
    Region _reg_19 = ((Region){ .slot = _slot_17, .expected_gen = ORTO_REGIONS[_slot_17].gen });
    Region aln_5 = _reg_19;
    Region _r_20 = aln_5;
    if (ORTO_REGIONS[_r_20.slot].gen != _r_20.expected_gen) abort();
    if (ORTO_REGIONS[_r_20.slot].used + (size_t)2 * sizeof(int) > ORTO_REGIONS[_r_20.slot].buffer_size) abort();
    int _off_21 = (int)ORTO_REGIONS[_r_20.slot].used;
    ORTO_REGIONS[_r_20.slot].used += (size_t)2 * sizeof(int);
    int* _slots_22 = (int*)(ORTO_REGIONS[_r_20.slot].buffer + _off_21);
    _slots_22[0] = 100;
    _slots_22[1] = 200;
    Array_int _arr_23 = ((Array_int){ .slot = _r_20.slot, .offset = _off_21, .len = 2, .expected_gen = _r_20.expected_gen });
    Array_int c_6 = _arr_23;
    Array_int _a_24 = a_2;
    int _i_25 = 0;
    if (ORTO_REGIONS[_a_24.slot].gen != _a_24.expected_gen) abort();
    if (_i_25 < 0 || _i_25 >= _a_24.len) abort();
    int _idx_26 = ((int*)(ORTO_REGIONS[_a_24.slot].buffer + _a_24.offset))[_i_25];
    Array_int _a_27 = b_4;
    int _i_28 = 0;
    if (ORTO_REGIONS[_a_27.slot].gen != _a_27.expected_gen) abort();
    if (_i_28 < 0 || _i_28 >= _a_27.len) abort();
    int _idx_29 = ((int*)(ORTO_REGIONS[_a_27.slot].buffer + _a_27.offset))[_i_28];
    Array_int _a_30 = c_6;
    int _i_31 = 0;
    if (ORTO_REGIONS[_a_30.slot].gen != _a_30.expected_gen) abort();
    if (_i_31 < 0 || _i_31 >= _a_30.len) abort();
    int _idx_32 = ((int*)(ORTO_REGIONS[_a_30.slot].buffer + _a_30.offset))[_i_31];
    int _let_result_33 = (((_idx_26 + _idx_29) + _idx_32) + a_2.len);
    if (ORTO_REGIONS[aln_5.slot].gen == aln_5.expected_gen) { if (!ORTO_REGIONS[aln_5.slot].is_stack) free(ORTO_REGIONS[aln_5.slot].buffer); ORTO_REGIONS[aln_5.slot].buffer = NULL; ORTO_REGIONS[aln_5.slot].buffer_size = 0; ORTO_REGIONS[aln_5.slot].used = 0; ORTO_REGIONS[aln_5.slot].gen++; ORTO_REGIONS[aln_5.slot].next_free = ORTO_REGION_FREE_HEAD; ORTO_REGION_FREE_HEAD = aln_5.slot; }
    int _let_result_34 = _let_result_33;
    if (ORTO_REGIONS[stk_3.slot].gen == stk_3.expected_gen) { if (!ORTO_REGIONS[stk_3.slot].is_stack) free(ORTO_REGIONS[stk_3.slot].buffer); ORTO_REGIONS[stk_3.slot].buffer = NULL; ORTO_REGIONS[stk_3.slot].buffer_size = 0; ORTO_REGIONS[stk_3.slot].used = 0; ORTO_REGIONS[stk_3.slot].gen++; ORTO_REGIONS[stk_3.slot].next_free = ORTO_REGION_FREE_HEAD; ORTO_REGION_FREE_HEAD = stk_3.slot; }
    int _let_result_35 = _let_result_34;
    if (ORTO_REGIONS[heap_1.slot].gen == heap_1.expected_gen) { if (!ORTO_REGIONS[heap_1.slot].is_stack) free(ORTO_REGIONS[heap_1.slot].buffer); ORTO_REGIONS[heap_1.slot].buffer = NULL; ORTO_REGIONS[heap_1.slot].buffer_size = 0; ORTO_REGIONS[heap_1.slot].used = 0; ORTO_REGIONS[heap_1.slot].gen++; ORTO_REGIONS[heap_1.slot].next_free = ORTO_REGION_FREE_HEAD; ORTO_REGION_FREE_HEAD = heap_1.slot; }
    return _let_result_35;
}