/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct Shape Shape;

typedef struct Sign Sign;

typedef int (*fn_Shape_to_int)(Shape);

typedef Sign (*fn_int_to_Sign)(int);

struct Shape {
    int tag;
    union {
        struct { int f0; } Circle;
        struct { int f0; int f1; } Rect;
        struct { int f0; } Square;
    } as;
};

struct Sign {
    int tag;
};

Sign sign_of(int n);

int area(Shape s);

int main(void);

Sign sign_of(int n) {
    Sign tmp_2;
    if ((n > 0)) {
        tmp_2 = ((Sign){ .tag = 0 });
    } else {
        Sign tmp_1;
        if ((n == 0)) {
            tmp_1 = ((Sign){ .tag = 1 });
        } else {
            tmp_1 = ((Sign){ .tag = 2 });
        }
        tmp_2 = tmp_1;
    }
    return tmp_2;
}

int area(Shape s) {
    Shape scrut_1 = s;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Circle */
            int r_1 = scrut_1.as.Circle.f0;
            match_result_2 = ((3 * r_1) * r_1);
            break;
        }
        case 1: { /* Rect */
            int w_2 = scrut_1.as.Rect.f0;
            int h_3 = scrut_1.as.Rect.f1;
            match_result_2 = (w_2 * h_3);
            break;
        }
        case 2: { /* Square */
            int s_4 = scrut_1.as.Square.f0;
            match_result_2 = (s_4 * s_4);
            break;
        }
        default: abort();
    }
    return match_result_2;
}

int main(void) {
    Shape s1_1 = ((Shape){ .tag = 0, .as = { .Circle = { .f0 = 3 } } });
    Shape s2_2 = ((Shape){ .tag = 1, .as = { .Rect = { .f0 = 4, .f1 = 5 } } });
    Shape s3_3 = ((Shape){ .tag = 2, .as = { .Square = { .f0 = 6 } } });
    int a_4 = area(s1_1);
    int b_5 = area(s2_2);
    int c_6 = area(s3_3);
    Sign sign_7 = sign_of((0 - 7));
    Sign scrut_1 = sign_7;
    int match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Positive */
            match_result_2 = 100;
            break;
        }
        case 1: { /* Zero */
            match_result_2 = 200;
            break;
        }
        case 2: { /* Negative */
            match_result_2 = 40;
            break;
        }
        default: abort();
    }
    int d_8 = match_result_2;
    return (((a_4 + b_5) + c_6) + d_8);
}