/* generated by orto */
#include <stdlib.h>

typedef struct Op Op;

typedef struct Stack Stack;

typedef int (*fn_int_to_int)(int);

typedef Stack (*fn_Stack_int_to_Stack)(Stack, int);

typedef Stack (*fn_to_Stack)(void);

typedef Stack (*fn_Stack_Op_to_Stack)(Stack, Op);

struct Op {
    int tag;
    union {
        struct { int f0; } Push;
    } as;
};

struct Stack {
    int top;
    int mid;
    int bot;
    int depth;
};

extern int putchar(int c);

Stack push(Stack s, int v);

int print_digit(int d);

Stack binop(Stack s, int result);

int print_int(int n);

Stack apply(Stack s, Op op);

Stack empty(void);

int main(void);

Stack push(Stack s, int v) {
    Stack _spread_1_1 = s;
    return ((Stack){ .top = v, .mid = s.top, .bot = s.mid, .depth = (s.depth + 1) });
}

int print_digit(int d) {
    return putchar((d + 48));
}

Stack binop(Stack s, int result) {
    Stack _spread_1_1 = s;
    return ((Stack){ .top = result, .mid = s.bot, .bot = 0, .depth = (s.depth - 1) });
}

int print_int(int n) {
    int tmp_1;
    if ((n < 10)) {
        tmp_1 = print_digit(n);
    } else {
        (void)(print_int((n / 10)));
        tmp_1 = print_digit((n % 10));
    }
    return tmp_1;
}

Stack apply(Stack s, Op op) {
    Op scrut_1 = op;
    Stack match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Push */
            int v_1 = scrut_1.as.Push.f0;
            match_result_2 = push(s, v_1);
            break;
        }
        case 1: { /* Add */
            match_result_2 = binop(s, (s.top + s.mid));
            break;
        }
        case 2: { /* Mul */
            match_result_2 = binop(s, (s.top * s.mid));
            break;
        }
        case 3: { /* Neg */
            Stack _spread_1_2 = s;
            match_result_2 = ((Stack){ .top = (0 - s.top), .mid = _spread_1_2.mid, .bot = _spread_1_2.bot, .depth = _spread_1_2.depth });
            break;
        }
        default: abort();
    }
    return match_result_2;
}

Stack empty(void) {
    return ((Stack){ .top = 0, .mid = 0, .bot = 0, .depth = 0 });
}

int main(void) {
    Stack s_1 = empty();
    Stack s_2 = apply(s_1, ((Op){ .tag = 0, .as = { .Push = { .f0 = 3 } } }));
    Stack s_3 = apply(s_2, ((Op){ .tag = 0, .as = { .Push = { .f0 = 4 } } }));
    Stack s_4 = apply(s_3, ((Op){ .tag = 1 }));
    Stack s_5 = apply(s_4, ((Op){ .tag = 0, .as = { .Push = { .f0 = 6 } } }));
    Stack s_6 = apply(s_5, ((Op){ .tag = 2 }));
    (void)(print_int(s_6.top));
    (void)(putchar(10));
    return s_6.top;
}