/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct Op Op;

typedef struct Stack Stack;

typedef int (*fn_int_to_int)(int);

typedef Stack (*fn_Stack_int_to_Stack)(Stack, int);

typedef Stack (*fn_to_Stack)(void);

typedef Stack (*fn_Stack_Op_to_Stack)(Stack, Op);

struct Op {
    int tag;
    union {
        struct { int f0; } Push;
    } as;
};

struct Stack {
    int top;
    int mid;
    int bot;
    int depth;
};

extern int putchar(int c);

Stack push(Stack s, int v);

int print_digit(int d);

Stack binop(Stack s, int result);

int print_int(int n);

Stack apply(Stack s, Op op);

Stack empty(void);

int main(void);

Stack push(Stack s, int v) {
    Stack _spread_1_1 = s;
    return ((Stack){ .top = v, .mid = s.top, .bot = s.mid, .depth = (s.depth + 1) });
}

int print_digit(int d) {
    return putchar((d + 48));
}

Stack binop(Stack s, int result) {
    Stack _spread_1_1 = s;
    return ((Stack){ .top = result, .mid = s.bot, .bot = 0, .depth = (s.depth - 1) });
}

int print_int(int n) {
    int tmp_1;
    if ((n < 10)) {
        tmp_1 = print_digit(n);
    } else {
        (void)(print_int((n / 10)));
        tmp_1 = print_digit((n % 10));
    }
    return tmp_1;
}

Stack apply(Stack s, Op op) {
    Op scrut_1 = op;
    Stack match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* Push */
            int v_1 = scrut_1.as.Push.f0;
            match_result_2 = push(s, v_1);
            break;
        }
        case 1: { /* Add */
            match_result_2 = binop(s, (s.top + s.mid));
            break;
        }
        case 2: { /* Mul */
            match_result_2 = binop(s, (s.top * s.mid));
            break;
        }
        case 3: { /* Neg */
            Stack _spread_1_2 = s;
            match_result_2 = ((Stack){ .top = (0 - s.top), .mid = _spread_1_2.mid, .bot = _spread_1_2.bot, .depth = _spread_1_2.depth });
            break;
        }
        default: abort();
    }
    return match_result_2;
}

Stack empty(void) {
    return ((Stack){ .top = 0, .mid = 0, .bot = 0, .depth = 0 });
}

int main(void) {
    Stack s_1 = empty();
    Stack s_2 = apply(s_1, ((Op){ .tag = 0, .as = { .Push = { .f0 = 3 } } }));
    Stack s_3 = apply(s_2, ((Op){ .tag = 0, .as = { .Push = { .f0 = 4 } } }));
    Stack s_4 = apply(s_3, ((Op){ .tag = 1 }));
    Stack s_5 = apply(s_4, ((Op){ .tag = 0, .as = { .Push = { .f0 = 6 } } }));
    Stack s_6 = apply(s_5, ((Op){ .tag = 2 }));
    (void)(print_int(s_6.top));
    (void)(putchar(10));
    return s_6.top;
}