/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[1] = { 0x00 };
#define ORTO_STATIC_BYTES_LEN 0

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct stackcalc__Op stackcalc__Op;

typedef struct stackcalc__Stack stackcalc__Stack;

typedef stackcalc__Stack (*fn_stackcalc__Stack_int_to_stackcalc__Stack)(stackcalc__Stack, int);

typedef int (*fn_int_to_int)(int);

typedef stackcalc__Stack (*fn_to_stackcalc__Stack)(void);

typedef stackcalc__Stack (*fn_stackcalc__Stack_stackcalc__Op_to_stackcalc__Stack)(stackcalc__Stack, stackcalc__Op);

struct stackcalc__Op {
    int tag;
    union {
        struct { int f0; } stackcalc__Push;
    } as;
};

struct stackcalc__Stack {
    int top;
    int mid;
    int bot;
    int depth;
};

extern int putchar(int c);

stackcalc__Stack stackcalc__apply(stackcalc__Stack s, stackcalc__Op op);

stackcalc__Stack stackcalc__binop(stackcalc__Stack s, int result);

stackcalc__Stack stackcalc__empty(void);

int stackcalc__print_int(int n);

stackcalc__Stack stackcalc__push(stackcalc__Stack s, int v);

int main(void);

int stackcalc__print_digit(int d);

stackcalc__Stack stackcalc__apply(stackcalc__Stack s, stackcalc__Op op) {
    stackcalc__Op scrut_1 = op;
    stackcalc__Stack match_result_2;
    switch (scrut_1.tag) {
        case 0: { /* stackcalc__Push */
            int v_1 = scrut_1.as.stackcalc__Push.f0;
            match_result_2 = stackcalc__push(s, v_1);
            break;
        }
        case 1: { /* stackcalc__Add */
            match_result_2 = stackcalc__binop(s, (s.top + s.mid));
            break;
        }
        case 2: { /* stackcalc__Mul */
            match_result_2 = stackcalc__binop(s, (s.top * s.mid));
            break;
        }
        case 3: { /* stackcalc__Neg */
            stackcalc__Stack _spread_1_2 = s;
            match_result_2 = ((stackcalc__Stack){ .top = (0 - s.top), .mid = _spread_1_2.mid, .bot = _spread_1_2.bot, .depth = _spread_1_2.depth });
            break;
        }
        default: abort();
    }
    return match_result_2;
}

stackcalc__Stack stackcalc__binop(stackcalc__Stack s, int result) {
    stackcalc__Stack _spread_1_1 = s;
    return ((stackcalc__Stack){ .top = result, .mid = s.bot, .bot = 0, .depth = (s.depth - 1) });
}

stackcalc__Stack stackcalc__empty(void) {
    return ((stackcalc__Stack){ .top = 0, .mid = 0, .bot = 0, .depth = 0 });
}

int stackcalc__print_int(int n) {
    int tmp_1;
    if ((n < 10)) {
        tmp_1 = stackcalc__print_digit(n);
    } else {
        (void)(stackcalc__print_int((n / 10)));
        tmp_1 = stackcalc__print_digit((n % 10));
    }
    return tmp_1;
}

stackcalc__Stack stackcalc__push(stackcalc__Stack s, int v) {
    stackcalc__Stack _spread_1_1 = s;
    return ((stackcalc__Stack){ .top = v, .mid = s.top, .bot = s.mid, .depth = (s.depth + 1) });
}

int main(void) {
    stackcalc__Stack s_1 = stackcalc__empty();
    stackcalc__Stack s_2 = stackcalc__apply(s_1, ((stackcalc__Op){ .tag = 0, .as = { .stackcalc__Push = { .f0 = 3 } } }));
    stackcalc__Stack s_3 = stackcalc__apply(s_2, ((stackcalc__Op){ .tag = 0, .as = { .stackcalc__Push = { .f0 = 4 } } }));
    stackcalc__Stack s_4 = stackcalc__apply(s_3, ((stackcalc__Op){ .tag = 1 }));
    stackcalc__Stack s_5 = stackcalc__apply(s_4, ((stackcalc__Op){ .tag = 0, .as = { .stackcalc__Push = { .f0 = 6 } } }));
    stackcalc__Stack s_6 = stackcalc__apply(s_5, ((stackcalc__Op){ .tag = 2 }));
    (void)(stackcalc__print_int(s_6.top));
    (void)(putchar(10));
    return s_6.top;
}

int stackcalc__print_digit(int d) {
    return putchar((d + 48));
}