/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[3] = { 0x68, 0x69, 0x0a };
#define ORTO_STATIC_BYTES_LEN 3

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef int (*fn_int_to_int)(int);

typedef int (*fn_Array_byte_int_to_int)(Array_byte, int);

typedef int (*fn_Array_byte_int_int_to_int)(Array_byte, int, int);

extern int putchar(int c);

int strings_advanced__print_loop(Array_byte s, int i);

int strings_advanced__write_alphabet(Array_byte a, int i, int n);

int main(void);

int strings_advanced__print_loop(Array_byte s, int i) {
    int tmp_4;
    if ((i >= s.len)) {
        tmp_4 = 0;
    } else {
        Array_byte _a_1 = s;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        (void)(putchar(((int)(_idx_3))));
        tmp_4 = strings_advanced__print_loop(s, (i + 1));
    }
    return tmp_4;
}

int strings_advanced__write_alphabet(Array_byte a, int i, int n) {
    int tmp_3;
    if ((i >= n)) {
        tmp_3 = 0;
    } else {
        Array_byte _a_1 = a;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2] = ((uint8_t)((65 + i)));
        (void)(0);
        tmp_3 = strings_advanced__write_alphabet(a, (i + 1), n);
    }
    return tmp_3;
}

int main(void) {
    Array_byte g1_1 = ((Array_byte){ .slot = 0, .offset = 0, .len = 3, .expected_gen = 1 });
    Array_byte g2_2 = ((Array_byte){ .slot = 0, .offset = 0, .len = 3, .expected_gen = 1 });
    (void)(strings_advanced__print_loop(g1_1, 0));
    (void)(strings_advanced__print_loop(g2_2, 0));
    int _n_1 = 64;
    if (_n_1 < 0) abort();
    if (ORTO_REGION_FREE_HEAD < 0) abort();
    int _slot_2 = ORTO_REGION_FREE_HEAD;
    ORTO_REGION_FREE_HEAD = ORTO_REGIONS[_slot_2].next_free;
    ORTO_REGIONS[_slot_2].buffer = malloc((size_t)_n_1);
    if (!ORTO_REGIONS[_slot_2].buffer) abort();
    ORTO_REGIONS[_slot_2].buffer_size = (size_t)_n_1;
    ORTO_REGIONS[_slot_2].used = 0;
    ORTO_REGIONS[_slot_2].next_free = -1;
    ORTO_REGIONS[_slot_2].is_stack = 0;
    Region _reg_3 = ((Region){ .slot = _slot_2, .expected_gen = ORTO_REGIONS[_slot_2].gen });
    Region r_3 = _reg_3;
    Region _r_4 = r_3;
    if (ORTO_REGIONS[_r_4.slot].gen != _r_4.expected_gen) abort();
    int _n_5 = 5;
    if (_n_5 < 0) abort();
    if (ORTO_REGIONS[_r_4.slot].used + (size_t)_n_5 * sizeof(uint8_t) > ORTO_REGIONS[_r_4.slot].buffer_size) abort();
    int _off_6 = (int)ORTO_REGIONS[_r_4.slot].used;
    ORTO_REGIONS[_r_4.slot].used += (size_t)_n_5 * sizeof(uint8_t);
    uint8_t* _slots_7 = (uint8_t*)(ORTO_REGIONS[_r_4.slot].buffer + _off_6);
    for (int _i_8 = 0; _i_8 < _n_5; _i_8++) _slots_7[_i_8] = ((uint8_t)(0));
    Array_byte _arr_9 = ((Array_byte){ .slot = _r_4.slot, .offset = _off_6, .len = _n_5, .expected_gen = _r_4.expected_gen });
    Array_byte buf_4 = _arr_9;
    (void)(strings_advanced__write_alphabet(buf_4, 0, 5));
    (void)(strings_advanced__print_loop(buf_4, 0));
    (void)(putchar(10));
    Array_byte _a_10 = buf_4;
    int _lo_11 = 1;
    int _hi_12 = 4;
    if (ORTO_REGIONS[_a_10.slot].gen != _a_10.expected_gen) abort();
    if (_lo_11 < 0 || _hi_12 < _lo_11 || _hi_12 > _a_10.len) abort();
    Array_byte _sl_13 = ((Array_byte){ .slot = _a_10.slot, .offset = _a_10.offset + _lo_11 * (int)sizeof(uint8_t), .len = _hi_12 - _lo_11, .expected_gen = _a_10.expected_gen });
    Array_byte mid_5 = _sl_13;
    (void)(strings_advanced__print_loop(mid_5, 0));
    (void)(putchar(10));
    Array_byte _a_14 = mid_5;
    int _i_15 = 0;
    if (ORTO_REGIONS[_a_14.slot].gen != _a_14.expected_gen) abort();
    if (_i_15 < 0 || _i_15 >= _a_14.len) abort();
    uint8_t _idx_16 = ((uint8_t*)(ORTO_REGIONS[_a_14.slot].buffer + _a_14.offset))[_i_15];
    int _let_result_17 = ((int)(_idx_16));
    if (ORTO_REGIONS[r_3.slot].gen == r_3.expected_gen) { if (!ORTO_REGIONS[r_3.slot].is_stack) free(ORTO_REGIONS[r_3.slot].buffer); ORTO_REGIONS[r_3.slot].buffer = NULL; ORTO_REGIONS[r_3.slot].buffer_size = 0; ORTO_REGIONS[r_3.slot].used = 0; ORTO_REGIONS[r_3.slot].gen++; ORTO_REGIONS[r_3.slot].next_free = ORTO_REGION_FREE_HEAD; ORTO_REGION_FREE_HEAD = r_3.slot; }
    return _let_result_17;
}