/* generated by orto */
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Region runtime: a global slab of region slots. Each slot is
* reused after its region is dropped (gen bumps so old handles
* see a mismatch and either abort or take the dangling branch).
* No allocation per region beyond the user-requested buffer.
* Slot 0 is reserved for the static string-literal pool. */
#define ORTO_REGION_SLOTS 4096
struct Region_slot {
    int gen;
    char* buffer;
    size_t buffer_size;
    size_t used;
    int next_free;   /* -1 if in use, else next free slot id */
    int is_stack;    /* 1 if buffer is stack memory (do not free) */
};
static struct Region_slot ORTO_REGIONS[ORTO_REGION_SLOTS];
static int ORTO_REGION_FREE_HEAD = -1;

static const uint8_t ORTO_STATIC_BYTES[14] = { 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2c, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x21, 0x0a };
#define ORTO_STATIC_BYTES_LEN 14

static void orto_init_regions(void) __attribute__((constructor));
static void orto_init_regions(void) {
    for (int i = 0; i < ORTO_REGION_SLOTS; i++) {
        ORTO_REGIONS[i].gen = 1;
        ORTO_REGIONS[i].next_free = i + 1;
    }
    ORTO_REGIONS[ORTO_REGION_SLOTS - 1].next_free = -1;
    /* slot 0 = static string pool, never freed */
    ORTO_REGIONS[0].buffer = (char*)ORTO_STATIC_BYTES;
    ORTO_REGIONS[0].buffer_size = sizeof(ORTO_STATIC_BYTES);
    ORTO_REGIONS[0].used = ORTO_STATIC_BYTES_LEN;
    ORTO_REGIONS[0].is_stack = 1;
    ORTO_REGIONS[0].next_free = -1;
    ORTO_REGION_FREE_HEAD = 1;
}
typedef struct { int slot; int expected_gen; } Region;

typedef struct { int slot; int offset; int len; int expected_gen; } Array_byte;

typedef int (*fn_int_to_int)(int);

typedef int (*fn_Array_byte_int_to_int)(Array_byte, int);

typedef int (*fn_Array_byte_to_int)(Array_byte);

extern int putchar(int c);

int strings_print__print_loop(Array_byte s, int i);

int strings_print__print(Array_byte s);

int main(void);

int strings_print__print_loop(Array_byte s, int i) {
    int tmp_4;
    if ((i >= s.len)) {
        tmp_4 = 0;
    } else {
        Array_byte _a_1 = s;
        int _i_2 = i;
        if (ORTO_REGIONS[_a_1.slot].gen != _a_1.expected_gen) abort();
        if (_i_2 < 0 || _i_2 >= _a_1.len) abort();
        uint8_t _idx_3 = ((uint8_t*)(ORTO_REGIONS[_a_1.slot].buffer + _a_1.offset))[_i_2];
        (void)(putchar(((int)(_idx_3))));
        tmp_4 = strings_print__print_loop(s, (i + 1));
    }
    return tmp_4;
}

int strings_print__print(Array_byte s) {
    return strings_print__print_loop(s, 0);
}

int main(void) {
    (void)(strings_print__print(((Array_byte){ .slot = 0, .offset = 0, .len = 14, .expected_gen = 1 })));
    return 0;
}