#!/bin/sh
# Build a single text bundle with the source that defines the language.
#
# Usage:
#   ./scripts/language_context.sh
#   ./scripts/language_context.sh /tmp/language_context.txt
#   ./scripts/language_context.sh - > language_context.txt

set -eu

cd "$(dirname "$0")/.."

output="${1:-language_context.txt}"

language_files() {
    printf '%s\n' \
        dune-project \
        bin/dune \
        bin/main.ml \
        lib/dune

    find lib -maxdepth 1 -type f \( -name '*.ml' -o -name '*.mli' \) | sort
    find std -maxdepth 1 -type f -name '*.orto' | sort

    if [ -f runtime_qbe.c ]; then
        printf '%s\n' runtime_qbe.c
    fi
}

write_bundle() {
    printf '%s\n' '# Teak/Orto Language Context'
    printf '\n'
    printf '%s\n' 'Generated by scripts/language_context.sh.'

    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        printf 'Commit: %s\n' "$(git rev-parse --short HEAD)"
        if [ -n "$(git status --short)" ]; then
            printf '%s\n' 'Worktree: dirty'
        else
            printf '%s\n' 'Worktree: clean'
        fi
    fi

    printf '\n'
    printf '%s\n' 'Includes: compiler driver, Dune metadata, AST/tokens/lexer/parser, resolve/lift/check/mono, C and QBE emitters, standard library modules, and QBE runtime support.'
    printf '%s\n' 'Excludes: examples, tests, generated C, docs, build output, and local agent/config files.'

    printf '\n%s\n\n' '## File Manifest'
    language_files

    printf '\n%s\n' '## Files'

    language_files | while IFS= read -r path; do
        printf '\n===== BEGIN FILE: %s =====\n' "$path"
        sed 's/\r$//' "$path"
        printf '\n===== END FILE: %s =====\n' "$path"
    done
}

if [ "$output" = "-" ]; then
    write_bundle
    exit 0
fi

mkdir -p "$(dirname "$output")"
tmp=$(mktemp "${TMPDIR:-/tmp}/teak_language_context.XXXXXX")
trap 'rm -f "$tmp"' EXIT HUP INT TERM
write_bundle > "$tmp"
mv "$tmp" "$output"
trap - EXIT HUP INT TERM

bytes=$(wc -c < "$output" | tr -d ' ')
files=$(language_files | wc -l | tr -d ' ')
printf 'wrote %s (%s files, %s bytes)\n' "$output" "$files" "$bytes"
